### ISSUE TITLE
hyper can not work with virtualbox on Mac OSX 10.11

### ISSUE THREAD

**Issue by carmark** [hyperhq/hyperd#109]
Since the update of Mac OSX broke some functions of Virtualbox, `hyper` could not work with VirtualBox on Mac OSX 10.11

**Comment by gnawux** [comment]
virtualbox 5.0.6 is out, need check the compatibility of it.

**Comment by carmark** [comment]
Two issues are found after my manual test with vbox 5.0.8.
* `run` command can not attach to the container
* `pull` command does not work

**Comment by gnawux** [comment]
close this issue, virtualbox support has been removed from the latest release
