### ISSUE TITLE
Using Hyper in Mac OS X and ports

### ISSUE THREAD

**Issue by jzarzuela** [hyperhq/hyperd#148]
Hi,
I usually use boot2docker to run my docker containers, but I want to get Hyper a try.

I've been trying to run tomcat example you give but I can't get it work. I don't know how to map ports and access it from my browser.

I have created a new version of the .pod file with this added elements (whole file is attached)
[tomcat-cpy.pod.zip](https://github.com/hyperhq/hyper/files/67477/tomcat-cpy.pod.zip)

:

```
"ports": [{
        "containerPort": 8080,
        "hostPort": 8787
        }]
```

And run the pod as: 
    hyper run --publish 8787:8787 -p /opt/hyper/examples/tomcat-cpy.pod 

But I can't get access to tomcat HTML response....

Maybe I don't know what the VM IP Address is (I'm using localhost).

Any help?

Thanks

**Comment by gnawux** [comment]
hi @jzarzuela , what's your OS X version? The virtualbox on 10.11 works different from the previous version, we are working on fix it. If you are on 10.11, please wait some time. Sorry for the inconvenience.

**Comment by jzarzuela** [comment]
Hi,
I have version 10.11.2. So maybe that's why it doesn't work properly.

Thanks.

2015-12-19 16:28 GMT+01:00 Xu Wang <notifications@github.com>:

> hi @jzarzuela <https://github.com/jzarzuela> , what's your OS X version?
> The virtualbox on 10.11 works different from the previous version, we are
> working on fix it. If you are on 10.11, please wait some time. Sorry for
> the inconvenience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperhq/hyper/issues/148#issuecomment-165996758>.
>



-- 
JZarzuela

**Comment by mindscratch** [comment]
@gnawux I'm also on on Mac OS 10.11.2, looking forward to trying hyper.sh on it.

**Comment by gnawux** [comment]
close this issue, virtualbox support has been removed from the latest release
