### ISSUE TITLE
proposal : an unified management  of IP address across host

### ISSUE THREAD

**Issue by xlgao-zju** [hyperhq/hyperd#157]
While we are implementing the live migration, we came across a problem that if we have two hosts (A and B), there is a container (IP: 192.168.123.1) on A and a container (IP:192.168.123.1) on B, when we migrate the container which is on A to B, there will be two containers that have same IP(192.168.123.1) on B.
So, I think an unified management  of IP address across host is necessary for live migration. I think etcd is a choice. And I would like to see some other advice.

**Comment by xiaods** [comment]
@xlgao-zju yeah, i don't think hyperd need care you ipam. please carefully design your policy to manage the ip pool. etcd is good options.

**Comment by xlgao-zju** [comment]
Yes, we use etcd to manage the IP address in live migration. And I think we can close this issue.
