### ISSUE TITLE
ubuntu 14.04 issues with hyperctl from git

### ISSUE THREAD

**Issue by zenny** [hyperhq/hyperd#268]
Compiled in ubuntu 14.04 from the git repo. Everything went well. But strange errors are popping up:

> $ sudo hyperctl list
> POD ID              POD Name            VM name             Status
> pod-BtkAFzMFqC      alpine-1051916546                       pending
> 
> $ ls /var/lib/hyper/hosts/
> pod-BtkAFzMFqC  pod-ssNYNDcTBw  pod-wptmdwMwzf
> 
> $ sudo hyperctl start pod-BtkAFzMFqC
> hyperctl ERROR: Error from daemon's response: stat /var/lib/hyper/hosts/pod-BtkAFzMFqC/**hosts**: no such file or directory

All default setups:

> $ cat /etc/hyper/config 
> Kernel=/var/lib/hyper/kernel
> Initrd=/var/lib/hyper/hyper-initrd.img
> Bios=/var/lib/hyper/bios-qboot.bin
> Cbfs=/var/lib/hyper/cbfs-qboot.rom

**Comment by zenny** [comment]
However the pre-compiled binary (hyper, not hyperctl) works fine when reinstalled.

It could be that hyperctl searches for the hosts directory inside the pods!?

**Comment by laijs** [comment]
thanks for report.
the new hyperd creates /var/lib/hyper/hosts/pod-BtkAFzMFqC/ via tmpfs and causes the problem. we will fix it later.

**Comment by zenny** [comment]
In the meantime, how to relocate /var/lib/hyper directory to somewhere else by changing hyper configuration except symlinking?

**Comment by zenny** [comment]
@laijs are you migrating to tmpfs from aufs, in that case? How will it affect the previous instances of hyper?

**Comment by laijs** [comment]
The hyperd always use vfs for hosts. But the recent hyperd uses tmpfs for dir of the hosts file, but the path is still /var/lib/hyper/hosts/${pod-id}/hosts. it doesn't affect the previous instances *in theory*.
(we try hard to make api/store stable, but it is not guaranteed since it is still under unstable development stage, and the newest hyperd/hyperctl are always recommended)

cloud you give me the result of `ls -l /var/lib/hyper/hosts/pod-BtkAFzMFqC/` and `ls -ld /var/lib/hyper/hosts/pod-BtkAFzMFqC/` please?

**Comment by zenny** [comment]
Here it comes:

```
# ls -l /var/lib/hyper/hosts/pod-BtkAFzMFqC/
total 0
# ls -ld /var/lib/hyper/hosts/pod-BtkAFzMFqC/
drwxr-xr-x 2 root root 4096 Apr 12 16:05 /var/lib/hyper/hosts/pod-BtkAFzMFqC/
```

**Comment by laijs** [comment]
the hosts file is missing. it was created from hyperd via tmpfs. it a known bug, we will fix it later.

**Comment by zenny** [comment]
> the new hyperd creates /var/lib/hyper/hosts/pod-BtkAFzMFqC/ via tmpfs and causes the problem. we will fix it later.

Is there a tentative roadmap when this aspect would be addressed?

**Comment by laijs** [comment]
github issue is the bugtracker

**Comment by laijs** [comment]
@zenny If you are interested the possible fix before merged, you can try/retest it with github.com/hyperhq/hyper/pull/259 

Thanks.

**Comment by zenny** [comment]
@laijs Pulled from the latest commit just a while ago including runv, compiled, but hyperd fails to run:
```
# /etc/init.d/hyperd start
# /etc/init.d/hyperd status
```
Log shows:

```
# cat /var/log/hyper/hyperd.ERROR 
Log file created at: 2016/04/14 08:50:12
Running on machine: MACHINE-GA-970A-D3
Binary: Built with gc go1.6 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
```

**Comment by laijs** [comment]
I don't know the script `/etc/init.d/hyperd`, could you direct launch it please?
`hyperd --nondaemon -v=3`

**Comment by zenny** [comment]
@laijs it is where the hyperd is located in the debian based distros and alpine linux, too which is equivalent to '`service hyperd start/stop/restart`' or '`systemctl start/stop hyperd.service`' in systemd, fyi.

**Comment by gnawux** [comment]
I suspect @zenny didn't update hyperstart to new version.
