### ISSUE TITLE
relocate /var/lib/hyper to a zfs 

### ISSUE THREAD

**Issue by zenny** [hyperhq/hyperd#269]
How to relocate /var/lib/hyper directory to somewhere else by changing hyper configuration without symlinking (`ln -s /tank/HYPER /var/lib/hyper`)?

**Comment by laijs** [comment]
https://github.com/hyperhq/hyper/blob/master/package/dist/etc/hyper/config#L3-L4

**Comment by zenny** [comment]
@laijs Thanks for the useful pointer.

**Comment by zenny** [comment]
After changing the Root= parameter to the new location hyperd service did not get killed:

```
# /etc/init.d/hyperd status
 * hyperd is running
# service hyperd stop
 * Stopping hyperd: hyperd                                                                                    [ OK ] 
# service hyperd status
 * hyperd is running
# killall hyperd
hyperd: no process found
```

**Comment by laijs** [comment]
Is /mnt/tank/HYPER/ a fresh new (empty) dir when the config is being changed?
What's the behavior of the same operations for the recent hyperd/hyperctl?

**Comment by zenny** [comment]
> Is /mnt/tank/HYPER/ a fresh new (empty) dir when the config is being changed?

Nope I stopped the hyperd service, copied all from /var/lib/hyper /mnt/tank/HYPER with all acl's saved with -a, and made changes to the config file accordingly and restarted the hyperd daemon.

What's the behavior of the same operations for the recent hyperd/hyperctl?

```
# hyperctl list
hyperctl ERROR: An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fhyper.sock/v0.5.0/list?item=pod: dial unix /var/run/hyper.sock: connect: no such file or directory
```

**Comment by laijs** [comment]
You can find why the hyperd exit from the log /var/log/hyper/hyperd.INFO /var/log/hyper/hyperd.ERROR.
The Root directory should be empty (except the kernel, hyper-initrd etc) when the first time it is relocated.

**Comment by bruceherve** [comment]
@laijs I know this is an old thread but I am new and get the same error when I run hyperctl info:
hyperctl ERROR: An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fhyper.sock/v0.8.1/list?item=pod: dial unix /var/run/hyper.sock: connect: no such file or directory

 **and here is the log as you suggested:**

Log file created at: 2017/06/24 20:57:49
Running on machine: localhost
Binary: Built with gc go1.8.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0624 20:57:49.122851   18247 config.go:38] config file: %!(EXTRA string=/etc/hyper/config)
I0624 20:57:49.123234   18247 config.go:72] [/etc/hyper/config] config items: &types.HyperConfig{ConfigFile:"/etc/hyper/config", Root:"/var/lib/hyper", Host:"", GRPCHost:"", StorageDriver:"", VmFactoryPolicy:"", Driver:"qemu", Kernel:"/var/lib/hyper/kernel", Initrd:"/var/lib/hyper/hyper-initrd.img", Bridge:"", BridgeIP:"", DisableIptables:false, EnableVsock:true, DefaultLog:"", DefaultLogOpt:map[string]string{}, logPrefix:"[/etc/hyper/config] "}
I0624 20:57:55.170355   18247 daemon.go:215] The hypervisor's driver is qemu
I0624 20:57:56.299793   18247 migration.go:23] Migrate lagecy persistent pod data, found: 0, migrated: 0
I0624 20:57:56.310088   18247 hyperd.go:189] Hyper daemon: 0.8.1 v0.4.0-912-g7a07c71
I0624 20:58:37.811799   18247 daemon.go:357] The daemon will be shutdown
I0624 20:58:37.811826   18247 daemon.go:358] Shutdown all VMs

**Comment by gnawux** [comment]
@bruceherve looks the daemon is shutdown before you run `hyperctl info`

```
I0624 20:58:37.811799 18247 daemon.go:357] The daemon will be shutdown
```

And you may open new issue if you find any issues.
