### ISSUE TITLE
Is it possible to add resources on the fly to a running pod/container?

### ISSUE THREAD

**Issue by zenny** [hyperhq/hyperd#287]
@gnawux Read your reply here with dead links: https://github.com/hyperhq/hyper/issues/130#issuecomment-155933705

But is it possible to allocate resources to a running pod or container?

I also got insufficient memory error as of below:

`OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fed74000, 6127616, 0) failed; error='Cannot allocate memory' (errno=12)`

**Comment by gnawux** [comment]
@zenny Currently, we don't change the resource of a Pod once it is created. This make the resource allocation and scheduling predictable. 

However, kvm/qemu allow us to hot plug cpu/memory to them. I think it is possible in the future.

**Comment by zenny** [comment]
I restarted the pod with:
```
 # hyperctl start -c 2 -m 8192 pod-YGLRVtQDSW
Successfully started the Pod(pod-YGLRVtQDSW)
```
Even after increasing the resources to two cpus and 8GB of memory, I am still getting:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fe84c000, 6770688, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 6770688 bytes for committing reserved memory.
```

**Comment by gnawux** [comment]
@zenny 

Unfortunately, it is a bug... we have already move all resource specification to the creating step, but forgot to remove the command line parameters, just like docker. 

I know the parameter looks useful, and it is reasonable to decide the resources when starting a pod, this should be add back in the future.

For now, could you try create another pod with bigger memory?

**Comment by zenny** [comment]
Please tag this as bug.

BTW, are resources thin provisioned or dedicated when one specifies, say --cpu=2 and --memory=8192?

**Comment by gnawux** [comment]
Whether do thin provisioning is the decision by scheduler, for a pod, you run it with 8GB memory, you have the ability to access them.

**Comment by zenny** [comment]
@gnawux as I have updated above at https://github.com/hyperhq/hyperd/issues/287#issuecomment-210407226, the resource allocation did not seem to have come into effect. Or did I miss something?

**Comment by gnawux** [comment]
@zenny do you mean the `memory` parameter?

```
[root@h8s-single hyperd]# ./hyperctl run --memory 768 -t busybox
/ # free
             total       used       free     shared    buffers     cached
Mem:        775980      23752     752228       3656          0       4000
-/+ buffers/cache:      19752     756228
Swap:            0          0          0
/ #
```

**Comment by gnawux** [comment]
close this issue due to not be active in a long period.
