### ISSUE TITLE
resolv.conf in container is empty

### ISSUE THREAD

**Issue by gao-feng** [hyperhq/hyperd#289]
overwrited by hyperstart, should we remove injecting file to image?

**Comment by gnawux** [comment]
Inject file is still useful, and insert `/etc/resolv.conf` is the default behavior. The hyperd process is:

- if `dns` is configured in pod spec, do not inject
- if user has inject or map `/etc/resolv.conf`, then do not inject

The solution should be: write `/etc/resolv.conf` if and only if the `dns` is configured
