### ISSUE TITLE
Stop Uninformed and Undocumented Rapid Changes

### ISSUE THREAD

**Issue by zenny** [hyperhq/hyperd#290]
@gnawux your last commit https://github.com/hyperhq/hyperd/commit/2072dd8e28a02a25ae6a819f81029b47a579e683 and previous commits have made a few uniformed and undocumented changes like
1.  [hyper.git](url) was changed [hyperd.git](url). 
2. A few days ago, `hyper` command was changed to `hyperctl`
3. Even after the above commit (https://github.com/hyperhq/hyperd/commit/2072dd8e28a02a25ae6a819f81029b47a579e683) the README.md to build from source (till these lines are written) still points to: `git clone https://github.com/hyperhq/hyper.git hyper`
4. And this screenshot (https://github.com/hyperhq/hyperd/raw/master/docs/static_files/hyper-run.png) has not been changed to reflect the changes
5. The command line has been shifted from hyper.sh domain to hypercontainer.io with a bunch of typos.
6. Instead of fixing the bugs reported, it seems as if the focus shifted to nomenclature. I think it should be _vice versa_ if you want to have more adopters.

Worth quoting Juliet from Shakespeare's play, 

```
What's in a name? That which we call a rose 
By any other name would smell as sweet." 
--Romeo and Juliet (II, ii, 1-2)

```

Since about a month of getting into this project, I am witnessing chaos rather than any order in this project, if I am not mistaken. Else apology in advance.

It could be a reason that the expression, `Chinese mind is like a spider's web`, was coined! wink ;-)

**Comment by Gnep** [comment]
@zenny 

As you may have noticed, we released our public container service a couple weeks ago. We had quite some discussion of naming, and decided to use Hyper_ and hyper.sh for the public service. 

To avoid more chaos in the future, we decided to rename Hyper to HyperContainer and the repo to hyperd. I fully understand your feeling. What we want is to avoid greater confusing in the future with the tradeoff of confusion to the current community (including you).

With that said, we will fix the typo and docs to get thing consistent soon.

**Comment by zenny** [comment]
@Gnep I saw your last commit (https://github.com/hyperhq/hyperd/commit/88cea8d63f5def05ffdc72ecc82bed12a85fdde3) to the README.md, you have yet not omitted the docker part in the `Installation` section:

> Ensure you are running Linux (kernel 3.8 or later) and have** Docker (version 1.5 or later)** and QEMU (version 2.0 or later) installed. 

However, what is the https://github.com/hyperhq/hypercli repo, if not `hyperctl`?

Before I further test, I would like to know exactly the roadmap and nomenclature without getting confused while compiling and using the tools. Xiexie!

**Comment by gnawux** [comment]
@zenny 

hypercli repo is the client for Hyper_ cloud, it is based on docker client and provide some hyper specified functions, such as floating IP associate, volume snapshot, etc. 

While the `hyperctl` is the control tool directly interact with `hyperd`, just like docker's `containerd` and its control tool.

I am very sorry for making you feel disappointed, however, I had to do in order to avoid further confusing. For hyperd + runv repo/project, our direction is to make it more compatible to docker behavior. And in the client side, we are working on providing a stabler and more efficient API interface based on gRPC.

And could you share your case with us? Although the project has not reach 1.0 yet (we want to make it reach 1.0 in this summer), we do not want to break your works when we do some changes.

**Comment by zenny** [comment]
@gnawux Thanks for updating. It would be good if you have some roadmap documents.

> And could you share your case with us?

I am planning to deploy in one of the production server in one of my datacenters. Namespace vulnerabilities didn't inspire me to deploy lxc or docker in production. The only part that I liked is the hw-based qemu-kvm isolation with this project above all,

> we do not want to break your works when we do some changes.

Frequent uninformed changes and  lack of update of proper documentation after the changes made life really a PITA.

> Although the project has not reach 1.0 yet (we want to make it reach 1.0 in this summer)

Good news, hope to see you meeting that deadline.

From what I witnessed with this project so far, your team lacks of someone with both technical and management skills who can field, canvass and manage your project more democratically with openness (could be me, shameless plug ;-) ). Just my two fen.

**Comment by Gnep** [comment]
@zenny 

The commit is a quick fix, not a complete one. What you will see is:

- HyperContainer (hyperd, hyperctl)
- Hypernetes=Kuberentes+HyperContainer+OpenStack Cinder/Neutron
- Hyper_: the public service, CLI hypercli 
- Hypernova: HyperContainer driver for OpenStack Nova
- HyperStack=Nova+Hypernova+Cinder+Neutron
- runV: hypervisor-based equivalent to runC

I hope this could help to clarify the confusion. We'd love to see your contribution on the project governance. Could you send an email to peng@hyper.sh to chat? I also want to invite you to our new public service.

Thanks!

**Comment by zenny** [comment]
@Gnep Still the binary package (https://hyper-install.s3.amazonaws.com/hyper-latest.tgz) is not updated, fyi.

Appreciate if you would advise Mr. Peng or Mr.Wang to write back?

My PGP key is:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: http://openpgpjs.org

xsBNBFcTxwEBCAC+G0MG+BHNGs8orGRobPV6jd+8RtT4XhXXEnuEjLA5uHz8
1OulvUS/qiq58Jo/KEnTn19rtyNiN7GmrLvo14Q0+mpFQEfrnzj2NCr1bf8w
l5r+CrIIb+xFEqf5dIHf3w1NNXgHwl6Z3QBflZsqaPHa8y5dhAqVlr1NS7EL
VgCifutAppl2Fcl05p4F5pQLKHMYCO+5gPMnMfnOOe4BTch0VOg8N4qkv0Px
JtSHjHucpivf4eJwznejYwDt/AtdyaB7LUC9N6yuLN+QYuB/mIo0YVU2wcgP
iwr8ITfDUz5Nx0MUm9hmTbOyj6ixNOVuYMmOvevCzzU0ULEkr99EMoAJABEB
AAHNHFplbm55IDxnYXJieXRyYXNoQGdtYWlsLmNvbT7CwHIEEAEIACYFAlcT
xwEGCwkIBwMCCRABOcPTK6+XKwQVCAIKAxYCAQIbAwIeAQAAD5gH/21f5PLm
ytP4rd9HLGKHTMQola/VKMoCMlA7zb1LLJKTCJayZmIproblTyWO8iSSkkaA
89gIifuCTvMJ8vh4WLTUfO0gr+41uZhLScYqAOoqgctCPsyrHxV4QBYAzGf7
1LAEymtYBSiKHhks4Jff190Czrfupz7AAuLxepS1/RIZbdmeYO2g8FWf4sIR
ZFKehNMSWlspxYGxXdAmGLX+xtHD+LNHqqnERsuatynR9oJ3G8WauD4CiNgW
IRyfxf2xZVj7J+bGzg7dl7IJNmp0UDTLqqsF2TFpURyfIAAAhb3WkQAaV5n1
osMST1BbCnWdGo5bjpReuBl3lQ5bIn3Gc3HOwE0EVxPHAQEIAL2Pq+od71kT
/lRMt+XDryOc1XTT5DJW7BUMXOjXXOZfWsuGTrqU3O1XYPWYzoZy9L+6zpII
On/auicvkUblWvrXkt4CIVIU1qDk6KpDKVKBiINy5sk7cTyjumbqxPmnVBK2
DHN27rLOnReCnFUmgIgbfgK0/un0oEnAHvsYdeg1ydipd2vVzx3aJ1TfQS1W
IBWN125EO4nKQ5Kl1XV7nWvlv+ZvrOmOWVeSl9jpyZvLJDmks0E/AIF4QBJF
K+NTME8+x7CwFDQwLGENXojeZOfsNHbln91KE1ZU1/QvzLHVqdZOo/s20Y7V
tjdUsiUPpVQcsSpXLzGKPCWz90M3Be8AEQEAAcLAXwQYAQgAEwUCVxPHAgkQ
ATnD0yuvlysCGwwAAL9hCACP7CY1fivXEN4X+l/C56l/nARrNVoZvJr4QHnF
9C/r5m6TLCMov0eOLg8IvZF7M0Ecyvq1IzNqbwQd+8mTA4tn+aND20fk2z08
floFL6fJykIyAGtRMwAb3HdC1pqexk/0pYxhoy9GtQzqvK/NbcPPdBDd1N7M
pKdXDVhXhx0R1K6UlMYfnyc9o171UYRPlFrmdBV7ZLC4KeBKqFEESKXaxyRg
D7E1FXGl1pDMh2QJNM/n9gVLJb0+znBsPG4jUNOctAOhRwF9Z23qsU6AGpOu
QhWG1alJz6d1T4sTgPdh+K1nMWNKGUzzayAKrRPTbnwLEijqqJPpIIDVzoai
py73
=JPvb
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by gnawux** [comment]
Thank you @zenny 

I know the binary package has not been updated. I think we should not modify a published package, and we will release new version after fix the current critical issues.

**Comment by zenny** [comment]
@gnawux In that case, I suggest you to tag the tgz with a 'version no.-stable' and clarify that the precompiled package does not reflect the chanes in git repo, particularly the binary command itself (I meant your recent move to `hyperctl`)

**Comment by Gnep** [comment]
@zenny plz sign up our beta at https://hyper.sh and let me know the email address you used. I'll approve ASAP.

**Comment by zenny** [comment]
@Gnep Yes I signed up a per your request, but have no idea how is it useful to me? You can derive my password from my PGP key and the username is Zenny.

My PGP key is:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: http://openpgpjs.org

xsBNBFcTxwEBCAC+G0MG+BHNGs8orGRobPV6jd+8RtT4XhXXEnuEjLA5uHz8
1OulvUS/qiq58Jo/KEnTn19rtyNiN7GmrLvo14Q0+mpFQEfrnzj2NCr1bf8w
l5r+CrIIb+xFEqf5dIHf3w1NNXgHwl6Z3QBflZsqaPHa8y5dhAqVlr1NS7EL
VgCifutAppl2Fcl05p4F5pQLKHMYCO+5gPMnMfnOOe4BTch0VOg8N4qkv0Px
JtSHjHucpivf4eJwznejYwDt/AtdyaB7LUC9N6yuLN+QYuB/mIo0YVU2wcgP
iwr8ITfDUz5Nx0MUm9hmTbOyj6ixNOVuYMmOvevCzzU0ULEkr99EMoAJABEB
AAHNHFplbm55IDxnYXJieXRyYXNoQGdtYWlsLmNvbT7CwHIEEAEIACYFAlcT
xwEGCwkIBwMCCRABOcPTK6+XKwQVCAIKAxYCAQIbAwIeAQAAD5gH/21f5PLm
ytP4rd9HLGKHTMQola/VKMoCMlA7zb1LLJKTCJayZmIproblTyWO8iSSkkaA
89gIifuCTvMJ8vh4WLTUfO0gr+41uZhLScYqAOoqgctCPsyrHxV4QBYAzGf7
1LAEymtYBSiKHhks4Jff190Czrfupz7AAuLxepS1/RIZbdmeYO2g8FWf4sIR
ZFKehNMSWlspxYGxXdAmGLX+xtHD+LNHqqnERsuatynR9oJ3G8WauD4CiNgW
IRyfxf2xZVj7J+bGzg7dl7IJNmp0UDTLqqsF2TFpURyfIAAAhb3WkQAaV5n1
osMST1BbCnWdGo5bjpReuBl3lQ5bIn3Gc3HOwE0EVxPHAQEIAL2Pq+od71kT
/lRMt+XDryOc1XTT5DJW7BUMXOjXXOZfWsuGTrqU3O1XYPWYzoZy9L+6zpII
On/auicvkUblWvrXkt4CIVIU1qDk6KpDKVKBiINy5sk7cTyjumbqxPmnVBK2
DHN27rLOnReCnFUmgIgbfgK0/un0oEnAHvsYdeg1ydipd2vVzx3aJ1TfQS1W
IBWN125EO4nKQ5Kl1XV7nWvlv+ZvrOmOWVeSl9jpyZvLJDmks0E/AIF4QBJF
K+NTME8+x7CwFDQwLGENXojeZOfsNHbln91KE1ZU1/QvzLHVqdZOo/s20Y7V
tjdUsiUPpVQcsSpXLzGKPCWz90M3Be8AEQEAAcLAXwQYAQgAEwUCVxPHAgkQ
ATnD0yuvlysCGwwAAL9hCACP7CY1fivXEN4X+l/C56l/nARrNVoZvJr4QHnF
9C/r5m6TLCMov0eOLg8IvZF7M0Ecyvq1IzNqbwQd+8mTA4tn+aND20fk2z08
floFL6fJykIyAGtRMwAb3HdC1pqexk/0pYxhoy9GtQzqvK/NbcPPdBDd1N7M
pKdXDVhXhx0R1K6UlMYfnyc9o171UYRPlFrmdBV7ZLC4KeBKqFEESKXaxyRg
D7E1FXGl1pDMh2QJNM/n9gVLJb0+znBsPG4jUNOctAOhRwF9Z23qsU6AGpOu
QhWG1alJz6d1T4sTgPdh+K1nMWNKGUzzayAKrRPTbnwLEijqqJPpIIDVzoai
py73
=JPvb
-----END PGP PUBLIC KEY BLOCK-----



```
