### ISSUE TITLE
File /usr/bin/qemu-system-x86_64 conflict with default kvm on CentOS 7

### ISSUE THREAD

**Issue by linfan** [hyperhq/hyperd#293]
Hyper v0.5.0 has a different version /usr/bin/qemu-system-x86_64 file, conflict with the one from default yum repo in CentOS 7.

```
# yum install kvm
...
# curl -sSL http://hypercontainer.io/install | bash
...
Transaction check error:
  file /usr/bin/qemu-system-x86_64 from install of qemu-hyper-2.4.1-2.el7.centos.x86_64 conflicts with file from package qemu-system-x86-2:2.0.0-1.el7.6.x86_64
```

**Comment by gnawux** [comment]
Hi @linfan , 

Many thanks for your report.

Yes,  `qemu-hyper` provide `qemu-system-x86_64`, I checked centOS official repo, there is not a `qemu-system-x86-2` in centOS 7.

There is a `qemu-system-x86` in `epel`, I think both  `qemu-hyper` and `qemu-system-x86` could work with our hyperd. However we suggest user use `qemu-hyper`.
