### ISSUE TITLE
Switch to grpclog?

### ISSUE THREAD

**Issue by peter-edge** [hyperhq/hyperd#299]
I see hyperd is using glog, which can be a pain as the only solution, especially for others that might eventually use parts of hyperd as a library. In grpc-go, we solved this with grpclog https://github.com/grpc/grpc-go/blob/master/grpclog/logger.go which allows the logger to be switched out by an end-user - glog is still used as the grpc-go default, but if someone wants to log to stderr, for example, with another logging package, it's easy to do. As an example, with my logging package, you can easily switch https://github.com/peter-edge/lion-go/blob/master/grpc/grpclion.go. You can also use a logrus logger directly with grpclog.

Since hyperd is using grpc, it might be nice to switch to grpclog instead of glog. Thoughts? Another abstract logging package I have is https://go.pedge.io/dlog, which gives a bigger function set, but since grpc (and grpc-gateway) both use grpclog, this might be something that interests you.

**Comment by feiskyer** [comment]
Thanks for advising, the grpc server is still on working and we may change the log lib in the future.

By the way, what's your usecase of using hyperd as a library?
