### ISSUE TITLE
Feature request: osx install with Homebrew

### ISSUE THREAD

**Issue by chiefy** [hyperhq/hyperd#30]
I was thinking it might be easier to install/upgrade the `hyper` cli via `brew`, and am trying to create a Homebrew formula, but I notice that you aren't tagging releases? The last one was `0.1`? 

Homebrew needs to d/l an artifact and compare it's hash locally, so tagging/releasing would be great!

**Comment by carmark** [comment]
Hello @chiefy ,

It will be great that you can create a Homebrew formula, thanks.  Now, I am doing refactor on the source code on Mac, and open it later, so I did not add tagging/releasing.  The latest `hyper` version on Mac is `0.3`, but the previous one(0.2) is for Linux(xen support).  I am not familiar with the process of Homebrew, can I use the 0.3 as the initial version for `hyper` in Homebrew?

Regards,

**Comment by chiefy** [comment]
@carmark yes, Homebrew simply needs a set of source files at a specific tagged version w/ SHA hash. Tagging 0.3 to start would be fine. Thanks.
