### ISSUE TITLE
possible missing reclaim resource when terminate hyperd 

### ISSUE THREAD

**Issue by gao-feng** [hyperhq/hyperd#305]
hyperd call vm.StopPod to terminate pod, and hyperHandlePodEvent is waiting for SHUTDOWN event to reclaim resource, but vm.StopPod may receive the SHUTDOWN event before hyperHandlePodEvent and hyperd doesn't wait for hyperHandlePodEvent to finish execute. this will cause some resources fail
to reclaim.

We can fix this by use callback chain to replace the fanout chan, make sure hyperHandlePodEvent finish the cleanup job before  vm.StopPod get the SHUTDOWN event.

**Comment by gnawux** [comment]
@gao-feng did you produced the problem? I think the `hyperHandlePodEvent` itself is a callback function, and should be called whenever the vm loop has new event.
