### ISSUE TITLE
Hyper starts pod, I get console and after few commands xen destroy hyper vm (Small network load somehow kills vm/pod)

### ISSUE THREAD

**Issue by puresoul** [hyperhq/hyperd#31]
Hi,

i got some very strange issue, everything launch normaly, I get "vm/pod/container" shell and after while whole thing stuck, console die and xen destroy vm. Only hyper list give me that

         POD ID                      POD Name             VM name    Status
      pod-odraXDudfq             ubuntu-6296703420                     succeeded

Can someone help me, what I'am doing wrong or what I may be missing?

Thanks

Here is some basic info....

uname -a
Linux w1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17) x86_64 GNU/Linux

xl info
host                   : w1
release                : 3.16.0-4-amd64
version                : #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17)
machine                : x86_64
nr_cpus                : 2
max_cpu_id             : 3
nr_nodes               : 1
cores_per_socket       : 2
threads_per_core       : 1
cpu_mhz                : 1821
hw_caps                : bfebfbff:20100800:00000000:00000900:0000e3bd:00000000:00000001:00000000
virt_caps              : hvm
total_memory           : 4095
free_memory            : 3022
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 5
xen_extra              : .2-pre
xen_version            : 4.5.2-pre
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder dom0_mem=1024M
cc_compiler            : gcc (Debian 4.9.2-10) 4.9.2
cc_compile_by          : root
cc_compile_domain      : nanox.cz
cc_compile_date        : Wed Jul 29 12:16:20 CEST 2015
xend_config_format     : 4

hyper info
Containers: 3
PODs: 1
Total Memory: 905072 KB
Operating System: Debian GNU/Linux 8 (jessie)

docker info
Containers: 3
Images: 4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 2
Total Memory: 883.9 MiB
Name: w1
ID: IMNK:SD2T:EHW5:I4GK:FCGR:SENG:FZZ3:HAQI:IJ4K:KEPI:JRLK:XGS4
WARNING: No memory limit support
WARNING: No swap limit support

XEN log:
qemu: terminating on signal 1 from pid 5693

HYPER log:
[HYPER INFO  0804 15:31:.11 06045 server.go] Calling GET /list
[HYPER INFO  0804 15:31:.11 06045 job.go] +job list(pod)
[HYPER INFO  0804 15:31:.11 06045 job.go] -job list(pod) OK
[HYPER INFO  0804 15:31:.20 06045 server.go] Calling POST /pod/run
[HYPER INFO  0804 15:31:.20 06045 job.go] +job podRun({"id":"ubuntu-6296703420","containers":[{"name":"ubuntu-6296703420","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":
[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""})
[HYPER INFO  0804 15:31:.20 06045 pod.go] {"id":"ubuntu-6296703420","containers":[{"name":"ubuntu-6296703420","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[]
,"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""}
[HYPER INFO  0804 15:31:.20 06045 init_comm.go] Wating for init messages...
[HYPER INFO  0804 15:31:.20 06045 xen.go] Start VM as domain 6
[HYPER INFO  0804 15:31:.26 06045 init_comm.go] Get init ready message
[HYPER INFO  0804 15:31:.26 06045 vm_states.go] begin to wait vm commands
[HYPER INFO  0804 15:31:.49 06045 vm_states.go] got spec, prepare devices
[HYPER INFO  0804 15:31:.50 06045 vm_states.go] pod start success
[HYPER INFO  0804 15:31:.50 06045 job.go] -job podRun({"id":"ubuntu-6296703420","containers":[{"name":"ubuntu-6296703420","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":
[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""}) OK
[HYPER INFO  0804 15:31:.50 06045 server.go] Calling GET /list
[HYPER INFO  0804 15:31:.50 06045 job.go] +job list(container)
[HYPER INFO  0804 15:31:.50 06045 job.go] -job list(container) OK
[HYPER INFO  0804 15:31:.50 06045 server.go] Calling POST /attach
[HYPER INFO  0804 15:31:.50 06045 job.go] +job attach(container, 0a919ef87a43a98efc3e18c8891b6062eae71073dfd57d9138323b329e69e2a5, y3ksovnx)
[HYPER INFO  0804 15:31:.50 06045 server.go] Calling POST /tty/resize
[HYPER INFO  0804 15:31:.50 06045 job.go] +job tty(pod-odraXDudfq, y3ksovnx, 51, 190)
[HYPER INFO  0804 15:31:.50 06045 job.go] -job tty(pod-odraXDudfq, y3ksovnx, 51, 190) OK
[HYPER INFO  0804 15:33:.20 06045 vm_states.go] Connection interrupted, quit...
[HYPER ERROR 0804 15:33:.20 06045 vm_states.go] Shutting down because of an exception: connection to VM broken
[HYPER WARN  0804 15:33:.30 06045 vm_states.go] Qemu did not exit in time, try to stop it
[HYPER ERROR 0804 15:33:.30 06045 vm_states.go] Shutting down because of an exception: vm terminating timeout
[HYPER ERROR 0804 15:33:.30 06045 init_comm.go] read init data failed
[HYPER ERROR 0804 15:33:.30 06045 tty.go] read tty data failed
[HYPER INFO  0804 15:33:.31 06045 job.go] -job attach(container, 0a919ef87a43a98efc3e18c8891b6062eae71073dfd57d9138323b329e69e2a5, y3ksovnx) OK
[HYPER INFO  0804 15:33:.32 06045 vm_states.go] Got VM shutdown event while terminating, go to cleaning up
[HYPER INFO  0804 15:33:.32 06045 vm_states.go] resources reclaimed, quit...
[HYPER INFO  0804 15:33:.32 06045 init_comm.go] vm channel closed, quit

**Comment by gao-feng** [comment]
@puresoul Hi, are  you using the hyper/hyper-kernel/hyper-initrd.image installed from hyper.sh or compile it yourself?

**Comment by puresoul** [comment]
Hi, first I try install by hyper.sh and got that issue, after that I compiled everything myself and problem still presist.

**Comment by gao-feng** [comment]
@puresoul sorry for late response, `qemu: terminating on signal 1 from pid 5693`  Can you check who is the pid 5693, is it hyperd? And you can run hyperd with -v=3, this will print more information. Thanks!

**Comment by puresoul** [comment]
so, that pid isn't hyperd and I can't track process to that pid. Here is log with -v=3, only thing what I've done in vm was apt-get update. Vm stuck in the middle of that process.

log of hyperd http://pastebin.com/CMdZp6vJ

**Comment by gao-feng** [comment]
@puresoul please reset hyperstart to this commit `https://github.com/hyperhq/hyperstart/commit/46ffda72bdd85009af7380fc81812d8b745a7ae6`, and have a try. We will update hyper to support NEXT message asap.

**Comment by puresoul** [comment]
It produce more output but still same problem, do you have some another guess to try? Thanks

http://pastebin.com/DFrWsZ9m

**Comment by gao-feng** [comment]
@puresoul Sorry for late response, Can you check if you replace the old initrd under /var/lib/hyper/ with the compiled new initrd? it seems like hyperstart are busy handling pts data and had no chance to handle control data. but this bug is fixed by hyperstart, so it's weired.

**Comment by puresoul** [comment]
could you post what revisions of xen and hyper is verified to works. Then I'll checkout source, build and try it once more? Thanks

**Comment by puresoul** [comment]
ok, so now i can't startup vm. Only that:

   root@w1:/etc/hyper# hyper run ubuntu
   hyper ERROR: QEMU response data is nil

   root@w1:/etc/hyper# cat /etc/hyper/config 
   Host= unix:///var/run/hyper.sock
   Bios=/var/lib/hyper/bios-qboot.bin
   Kernel=/var/lib/hyper/kernel
   Initrd=/var/lib/hyper/hyper-initrd.img
   Bridge=hyper0

hyperd:
http://pastebin.com/Pt2DTmdm

**Comment by puresoul** [comment]
Ok, so I got it finaly working. xen 4.6rc, hyper-0.2dev and vanila kernel+initrd from installer. One thing that i changed was qemu-system-x86_64 binary. Xen qemu-system-i386 was maybe the problem. Installed qemu from repo and it's working... You may close this issue, thanks

**Comment by gao-feng** [comment]
@puresoul The successful case is running qemu without hardware virtualization(xen or kvm)?
`Still got hyper runing in dom0 and no as domU` what's this means? the error case is running hyper in domU?

**Comment by puresoul** [comment]
hyper vm wouldn't show in "xl list", so it's runing in dom0, and no at xen....

**Comment by gnawux** [comment]
@puresoul did your xen compiled with virtfs support 

    ./configure --with-extra-qemuu-configure-args="--enable-virtfs"

> note the double u, it should be double u for  xen 4.5

reference this doc: https://docs.hyper.sh/trouble_shooting/xen.html

**Comment by puresoul** [comment]
I'll try it, tahnks

**Comment by puresoul** [comment]
so, after while i got a question. Maybe here is bad place for that. I can't get from xen qemu-system-x86_64 binary, and qemu-system-i386 isn't compatible


[HYPER INFO  1102 12:06:00 01624 init_comm.go] [:45] [console] This kernel requires an x86-64 CPU, but only detected an i686 CPU.
[HYPER INFO  1102 12:06:00 01624 init_comm.go] [:45] [console] Unable to boot - please use a kernel appropriate for your CPU.

**Comment by puresoul** [comment]
On same machine. Installed stock hyper by curl/bash installation with xen 4.6. New bunch of errors occured. It but may be my own fault?

http://pastebin.com/c32LiEmY

**Comment by gnawux** [comment]
@puresoul panic is program fault definitely, but I can't tell if this is because of new behavior of xen 4.6, and will investigate it.

for the `i386` and `x86_64` problem, and xen always use `qemu-system-i386` by default. As xen does not rely on qemu for CPU emulation, this should not because of qemu build target. I wonder is this mean you build xen itself for i386 target. PS: I just guess the reason, and I am not sure about xen itself.

**Comment by puresoul** [comment]
I'am not build xen for i386 and because as xen does not rely on qemu for CPU emulation, I don't understand what I'am doing wrong.

**Comment by puresoul** [comment]
ok, another strange things. Just overwrite hyper with own compiled one. Now I got hyper vm/pod running in xen:

   root@w1:/etc/hyper# xl list
   Name                                        ID   Mem VCPUs	State	Time(s)
   Domain-0                                     0  2048     2     r-----    2054.9
   vm-mpTJiIAepG                                6   128     1     -b----       1.5

but somehow my issues now is again related to network. Now network is broken and if try manage eth0, vm/pod again crashes...

**Comment by gnawux** [comment]
The git repo is ahead of the binary. And we will look into the network issue

**Comment by puresoul** [comment]
that was about mounth old revision, by the way...

**Comment by puresoul** [comment]
there may be some problem with hyper bridge settings. If I network-detach interface and then network-attach, then network works over xen bridge

**Comment by gnawux** [comment]
We will test with the new code and publish a new release later....

**Comment by puresoul** [comment]
Hyperd log from last testings

http://pastebin.com/96WsWas8

**Comment by puresoul** [comment]
So I compiled actual revision a same problem with network presist. But now some new stuff appers at log,

http://pastebin.com/GC76KKLM

**Comment by gnawux** [comment]
@puresoul 
as you are using a new version of hyper, you can use `./hyper run -t ubuntu /bin/bash`, the `-t` flag for tty prompt. This may not relate with the problem, just a hint

**Comment by puresoul** [comment]
ok, I'll try

**Comment by puresoul** [comment]
ok, even updated hyperstart won't help. This is weird. Can I somehow enforce another network frontend/backend. Maybe it's related to netback/netfront

**Comment by gnawux** [comment]
@puresoul have you ever tried other images, such as busybox, nginx, etc.? I am afraid it is not pure network issue, might be low memory or something else.

**Comment by puresoul** [comment]
nope, so I'll try it

**Comment by puresoul** [comment]
sorry, misstype. Ok, I'll try

**Comment by gao-feng** [comment]
@puresoul What's the memory size of pod? can you try again with bigger memory?
https://docs.hyper.sh/reference/podfile.html

**Comment by puresoul** [comment]
I pull changes from git on hyper, runv and hyperstart. Recompile and start pod with 512mb. If I starts same apt-get with only main repo, it runs ok. After I add universe and multiverse, same situation. Freez and shutdown, it is maybe related to ubuntu image. I may try debian or anything else also....

http://pastebin.com/9EXCMeih

**Comment by puresoul** [comment]
won't resolv. Just drop hyper in favour of LXD.
