### ISSUE TITLE
Ctrl-C will detach tty but not kill the process in container

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/hyperd#336]
I attach a running pod and run command "ping 127.0.0.1" in it.
Then I try to input Ctrl-C to stop the process , but the result is I detach the Pod and the process is still running.The detail is showed as follow:

monster@monster:~/go/src/github.com/hyperhq/hyperd$ sudo ./hyperctl attach pod-DsfXyWajPy
Attach tag is t52xbqe3
ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.242 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.056 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.043 ms
^Cmonster@monster:~/go/src/github.com/hyperhq/hyperd$ sudo ./hyperctl attach pod-DsfWajPy
Attach tag is 5wn5oavp
64 bytes from 127.0.0.1: seq=7 ttl=64 time=0.056 ms
64 bytes from 127.0.0.1: seq=8 ttl=64 time=0.113 ms
64 bytes from 127.0.0.1: seq=9 ttl=64 time=0.058 ms
^Cmonster@monster:~/go/src/github.com/hyperhq/hyperd$

The commit of hyperd is dc966a88ab87
The commit of runv is bf2bb08511e

**Comment by laijs** [comment]
when the container tty is disabled, the ctrl-c is sent to hyperctl itself only. when ctrl-c is received, the hyperctl detach without stop the container. we should keep hyperctl running in this case.
