### ISSUE TITLE
fix the problem of the detachkey

### ISSUE THREAD

**Issue by laijs** [hyperhq/hyperd#337]
problem: https://github.com/docker/docker/issues/21769
fixed by: https://github.com/docker/docker/pull/22943
the corresponding code: https://github.com/hyperhq/runv/blob/166a81b1f1718b572c2a601580bf609dae75bd48/hypervisor/tty.go#L368-L380

the reason this issue is posted here is that detachkey is the behavior of hyperd, not runv.
the detachkey functionality will be moved to hyperd.

**Comment by gnawux** [comment]
Could we close this issue? @laijs
