### ISSUE TITLE
add volume support in `hyperctl run` command line

### ISSUE THREAD

**Issue by laijs** [hyperhq/hyperd#341]

**Comment by crook** [comment]
dup with #383

**Comment by laijs** [comment]
#383: when creating new containers in sandbox(pod)
here: when creating a new pod via hyperctl run without "-p pod.json"

**Comment by crook** [comment]
ok, I would like to take this enhancement. please assign this issue to me.

**Comment by laijs** [comment]
Ok, you can do it, but I failed to set the "Assignees" in the right panel of the github.

https://github.com/hyperhq/hyperd/blob/master/client/run.go#L198

**Comment by crook** [comment]
@laijs，here is the patch, please  help review.

btw, im still confused the above two issue,,can you explain more detail? thanka
