### ISSUE TITLE
hyper support checkpoint and restore

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/hyperd#35]
# dibs Now I have already made hyper support checkpoint and restore.If you use aufs docker image,you cant do it because of virtfs.If you use devicemapper docker image, it will be OK.Then I plan to make migrate between two physical host possible.

**Comment by carmark** [comment]
Hi @YaoZengzeng 

Thanks for your work, it will be interesting if you have any update.

Regards,

**Comment by resouer** [comment]
we can close this issue as #123 is on. @gnawux
