### ISSUE TITLE
Clarification on Minimum Requirements

### ISSUE THREAD

**Issue by ibmendoza** [hyperhq/hyperd#356]
On README.md,

Requirements
    QEMU 2.0 or later
    Xen 4.5 and VT enabled host (for Xen support)

should be rewritten as

```
KVM (QEMU 2.0 or later)
Xen (4.5 or later)
VirtualBox (Mac OS X)
```

to match what was written at https://github.com/hyperhq/runv

**Comment by xiaods** [comment]
currently the virtualbox is not working now
