### ISSUE TITLE
The status of container doesn't update in time

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/hyperd#357]
I try to kill one container in the pod which has more than one container.
From the log of hyperd, the container has been killed successfully . But from “hyperctl list container”, the container is still running.

monster@ubuntu:~/go/src/github.com/hyperhq/hyperd$ sudo ./hyperctl kill 29050b5a51a46446bacfa220062d681155692b177c960e02ee0381da5f66d620
monster@ubuntu:~/go/src/github.com/hyperhq/hyperd$ sudo ./hyperctl list container
Container ID                                                       Name                 POD ID              Status
29050b5a51a46446bacfa220062d681155692b177c960e02ee0381da5f66d620   busybox-2783395596   pod-MRyVjWNYxn      running
5c1bc9701fc2ec2681f423cfe9b12639ed8fda4ff55b720d23a9df135c1d357f   busybox-6050387386   pod-MRyVjWNYxn      running

**Comment by gao-feng** [comment]
Please try the latest hyperd, this should be fixed
