### ISSUE TITLE
UserServiceBackend json fields `hostip` and `hostport` will be changed to `hostIP` and `hostPort`

### ISSUE THREAD

**Issue by resouer** [hyperhq/hyperd#370]
In #369 we changed fields in `UserServiceBackend` to follow code style convention in the existing code. This makes the json fields change from `hostip` and `hostport` to `hostIP` and `hostPort`.

Record it here to remind us to update affected codes in hypernetes and other restful clients once #369  in.

```
type UserServiceBackend struct {
	HostIP   string `protobuf:"bytes,1,opt,name=hostIP" json:"hostIP,omitempty"`
	HostPort int32  `protobuf:"varint,2,opt,name=hostPort" json:"hostPort,omitempty"`
}
```

**Comment by feiskyer** [comment]
Please also add `serviceIP` and  `servicePort` according to https://github.com/hyperhq/hyperd/pull/369/files#diff-f325a92d451852ea8923aaa3a50731beR322
