### ISSUE TITLE
the options of the APP are eaten if the options are also the options for `hyperctl run/exec`

### ISSUE THREAD

**Issue by laijs** [hyperhq/hyperd#381]
`hyperctl run busybox uname -a`

the `-a` will be eaten.

`hyperctl run busybox uname -t` should be error, but `-t` is eaten and avoid the error.

**Comment by gnawux** [comment]
with `gflag.PassAfterNonOption`, the flags after first non-option arg will be pass as arguments. It has been included in commit 7481c54f0ebed4d3019adf5c3679d4512803e27d

**Comment by laijs** [comment]
@gnawux gflag.PassAfterNonOption is not added to `hyperctl exec` yet

**Comment by gnawux** [comment]
add it to exec in #561

**Comment by gnawux** [comment]
already fixed in the latest release
