### ISSUE TITLE
Support hotadd volume when creating new containers

### ISSUE THREAD

**Issue by feiskyer** [hyperhq/hyperd#383]

**Comment by crook** [comment]
what does hotadd mean?can you show en example?

do you mean the container can auto resan the newly attached volume?

**Comment by crook** [comment]
what does hotadd mean?can you show en example?

do you mean the container can auto resan the newly attached volume?

**Comment by gnawux** [comment]
no, just volumes for the new containers.

**Comment by gnawux** [comment]
@feiskyer could we close this issue now?

**Comment by feiskyer** [comment]
@gnawux Yep, already done.
