### ISSUE TITLE
Integrate with docker swarm?

### ISSUE THREAD

**Issue by kevinsimper** [hyperhq/hyperd#392]
Is there a way to use this with docker swarm, so that the manager starts hyper containers instead of normal docker containers?

**Comment by resouer** [comment]
There's existing project to integrate containerd + runv, see: https://blog.hyper.sh/runv-bring-isolation-to-docker.html

**Comment by xiaods** [comment]
i don't think swarm is good match for hyper.  it should be alternative solution is build a swarmkit on hyperd.
