### ISSUE TITLE
failed to run

### ISSUE THREAD

**Issue by keyolk** [hyperhq/hyperd#393]
Hello.
I'm newbie on this project.
I got some error when I trying to launch hyper with tomcat image.

below is some informations

$ hyperctl version
The hyperctl version is 0.6.0

$ sudo hyperctl info
Images: 6
Containers: 1
PODs: 1
Storage Driver: devicemapper
  Pool Name: docker-8:1-1457795-pool
  Pool Blocksize: 65.54 kB
  Base Device Size: 107.4 GB
  Backing Filesystem: xfs
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data Space Used: 684.4 MB
  Data Space Total: 107.4 GB
  Data Space Available: 24.48 GB
  Metadata Space Used: 1.642 MB
  Metadata Space Total: 2.147 GB
  Metadata Space Available: 2.146 GB
  Udev Sync Supported: true
  Deferred Removal Enabled: false
  Deferred Deletion Enabled: false
  Deferred Deleted Device Count: 0
  Data loop file: /var/lib/hyper/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/hyper/devicemapper/devicemapper/metadata
  Library Version: 1.02.130 (2016-07-06)
Hyper Root Dir: /var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: 
Total Memory: 16.37 MB
Operating System: Apricity OS

$ cat /etc/os-release 
NAME="Apricity OS"
ID=apricity
PRETTY_NAME="Apricity OS"
ANSI_COLOR="0;36"
HOME_URL="https://www.apricitylinux.org/"
SUPPORT_URL="https://bbs.apricitylinux.org/"
BUG_REPORT_URL="https://bugs.apricitylinux.org/"

$ uname -a
Linux keyolk-book 4.4.2-6ph #1 SMP Mon Jun 13 20:01:22 KST 2016 x86_64 GNU/Linux

$ sudo hyperctl run -d tomcat
POD id is pod-IXdhgfJvlc
hyperctl ERROR: Error from daemon's response: VM vm-qVNzVTTGeS start failed with code 7: Start POD failed

$ sudo hyperctl list  
POD ID              POD Name            VM name             Status
pod-IXdhgfJvlc      tomcat-0637936943                       pending

$ cat /var/log/hyper/hyperd.ERROR
Log file created at: 2016/07/13 14:38:37
Running on machine: keyolk-book
Binary: Built with gc go1.6.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0713 14:38:37.756843    2002 vm_states.go:278] Shutting down because of an exception: Start POD failed
E0713 14:38:37.757073    2002 vm_states.go:518] Start POD failed
E0713 14:38:37.757112    2002 run.go:77] VM vm-qVNzVTTGeS start failed with code 7: Start POD failed
E0713 14:38:37.757127    2002 server.go:170] Handler for POST /v0.6.0/pod/start returned error: VM vm-qVNzVTTGeS start failed with code 7: Start POD failed
E0713 14:38:37.802981    2002 init_comm.go:99] read init data failed
E0713 14:38:37.803103    2002 tty.go:92] read tty data failed

is anyone know why it failed ?

**Comment by gao-feng** [comment]
@keyolk Hello, can you show the  /var/log/hyper/hyperd.INFO?

**Comment by gnawux** [comment]
close this issue due to long time inactive, reopen this if anybody has similar problem and more information.
