### ISSUE TITLE
Either disable the cbfs rom or provide it

### ISSUE THREAD

**Issue by marcochiappero** [hyperhq/hyperd#395]
Hello, I'm using the pre-packaged (CentOS rpms) 0.6.0 release which comes with the /etc/hyper/config file. According to the out-of-the-box configuration, the cbfs images is searched for and used, but it's not actually provided by hyperstart, so to make it work the user has to comment out the cbfs related line (which is not documented anywhere).

Either disable the use of the cbfs rom in hyper-container by default or provide it in hyperstart.

**Comment by gnawux** [comment]
Hi @marcochiappero , thanks for reporting, and sorry for the inconvenience.

Please disable it, the cbfs is inherited from the previous versions and will be removed in the future release.

**Comment by marcochiappero** [comment]
Great, thank you!
