### ISSUE TITLE
ubuntu `apt-get update` failed with aufs storage driver

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hyperd#399]
With `aufs` storage driver enabled,  when execute `apt-get update` in a ubuntu image container, will get a error. Like this
```
Ign http://mirrors.aliyun.com trusty InRelease
Hit http://mirrors.aliyun.com trusty-updates InRelease
Get:1 http://mirrors.aliyun.com trusty-backports InRelease [65.9 kB]
E: Unable to determine file size for fd 7 - fstat (2: No such file or directory)
``` 

It seems a 9pfs problem, post just in case someone meet the same problem.
An easy workaround is not use `aufs` storage driver when using ubuntu image.

**Comment by bergwolf** [comment]
Looks like https://github.com/hyperhq/hyperstart/issues/74

Are you using a guest kernel with https://github.com/hyperhq/hyperstart/blob/master/build/kernel_patch/0001-HACK-9P-always-use-cached-inode-to-fill-in-v9fs_vfs_.patch ?

An easy way to verify is to run the test program mentioned in https://github.com/hyperhq/hyperstart/issues/74#issuecomment-214393486

**Comment by Crazykev** [comment]
yep, seems this patch has fixed it. It's the same problem.
