### ISSUE TITLE
Is there a hyperctl binary for OSX?

### ISSUE THREAD

**Issue by apobbati** [hyperhq/hyperd#407]
Is there a binary for `hyperctl` for OSX? If so, is there any way I can use it with the [Hyper](https://www.hyper.sh) CaaS ?

I haven't been able to find a binary in Github Releases.

**Comment by carmark** [comment]
Hello @apobbati ,

You may download the binary on mac from [here](https://hyper-install.s3.amazonaws.com/hyper-mac.bin.zip), you can find more information on [doc](https://docs.hyper.sh/GettingStarted/install.html). 

PS. The `brew install` is waiting approved by homebrew, so the current version does not work.

Thanks,
