### ISSUE TITLE
Curl-to-bash installation

### ISSUE THREAD

**Issue by KenanSulayman** [hyperhq/hyperd#411]
Hey,

there are some issues with the current installation process:
- `http://hypercontainer-install.s3.amazonaws.com/hyper-latest.tgz`<sup>[1]</sup> has a `hyper` command as opposed to `hyperctl`
- The installation script checks for `hyperctl`, causing the script to abort the installation (https://gist.github.com/KenanSulayman/b4922435a6a48a35c1f8ed7bd89942cf#file-hyper-sh-L323)
- Patching out the check for `hyperctl` allows the installation to succeed.

I'd prefer the `hyper` CLI over `hyperctl`, because it feels much better. Was it changed intentionally or by accident?

-- kenan

<sup>[1]</sup> Tarball meta data:

```
$ curl http://hypercontainer-install.s3.amazonaws.com/hyper-latest.tgz -I
HTTP/1.1 200 OK
x-amz-id-2: XmITmm7f6abIPQRrC7ZLKY52B/mnr+gYF2ueQ2evJlfyoqKw2niYVKM6OaiUzQEk0Chj0YRVivc=
x-amz-request-id: CBFD90C91EDC57DB
Date: Sun, 21 Aug 2016 01:07:36 GMT
Last-Modified: Wed, 20 Jul 2016 10:38:28 GMT
ETag: "78a5313cb515447a80cec560dd52515f"
x-amz-meta-s3b-last-modified: 20160206T185956Z
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 21844529
Server: AmazonS3

$ shasum -a 256 hyper-latest.tgz
039aa30d05e28c209b6b95b33d3883557f55fb4d04fe09ee1f5a1bccc38ab98b  hyper-latest.tgz
```

P.s.: there's a typo here: https://gist.github.com/KenanSulayman/b4922435a6a48a35c1f8ed7bd89942cf#file-hyper-sh-L92

**Comment by laijs** [comment]
> Was it changed intentionally or by accident?

`hyper` had been changed to be the client command line of the hyper cloud since the hyper cloud was announced.  And the controlling tool for hyperd(hypercontainer) was renamed to `hyperctl` at the same time. sorry for the confusion.
