### ISSUE TITLE
The binary tarball URL is invalid

### ISSUE THREAD

**Issue by sameo** [hyperhq/hyperd#425]
When curl'ing https://hyper-install.s3.amazonaws.com/hyper-latest.tgz, I get the following:

```
<Error>
 <Code>AccessDenied</Code>
 <Message>Access Denied</Message>
 <RequestId>89C277FCA6C91CEF</RequestId>
 <HostId>
    hVZn277zKtIccN/UCYaML09LZW1sDFzL2ETjkwE9ULC85PMiyuZrN24kR5q4xFp4cLTHU6Qugas=
 </HostId>
</Error>
```

**Comment by gnawux** [comment]
The address was move to https://s3-us-west-1.amazonaws.com/hypercontainer-install/hyper-latest.tgz  

But the static build is out of date. We have RPMs for redhat and fedora, and we will provide deb packages in days.

Could you tell us where do you get the link? We will update it.

**Comment by sameo** [comment]
@gnawux I got it from the hyperd README.md.
Are you going to update the static builds ?

**Comment by gnawux** [comment]
@sameo Thank you!

We will try, however, it's not easy to build a static version because we have more dependencies in recent version. (devicemapper, libvirt, etc.)  It is possible if we build a static binary without supporting libvirt some others.

Which distro are you working on?

**Comment by sameo** [comment]
@gnawux I was trying to run hyperd on Clear Linux, and I got it figured out. So please don't bother generating static files, at least not for me :)
