### ISSUE TITLE
Please update the centos rpm to latest version

### ISSUE THREAD

**Issue by vitan** [hyperhq/hyperd#435]
Here [the section](RPMs for CentOS/RHEL7) in http://docs.hypercontainer.io/get_started/install/linux.html give the 0.5 instead of latest 0.6 rpm repo. Please update it

**Comment by xiaods** [comment]
install bash is up to date

**Comment by vitan** [comment]
I am using `curl -sSL http://hypercontainer.io/install | bash` to bypass it

**Comment by gnawux** [comment]
The download urls in document has been updated to 0.7.0 (https://github.com/hyperhq/docs.hypercontainer.io/pull/19), together with deb packages (https://github.com/hyperhq/docs.hypercontainer.io/pull/20).

Thanks for report.
