### ISSUE TITLE
Does hyper support host network?

### ISSUE THREAD

**Issue by GrantLajs** [hyperhq/hyperd#452]
When I run docker command "docker run --net=host ...", the container shares network config with the host computer. 

Does hyper also support the network mode sharing the same with host OS?

Any response is appreciated!

**Comment by laijs** [comment]
no, the pod is running inside a VM. it is extremely hard to share the same network or even netns between host  and vm. it requires some very fancy features to enable the sharing such as pvcall(http://marc.info/?l=xen-devel&m=147639616310487&w=2).

**Comment by GrantLajs** [comment]
I see. Thank @laijs  very much!
