### ISSUE TITLE
How can processes inside pod communicate with processes on the host?

### ISSUE THREAD

**Issue by GrantLajs** [hyperhq/hyperd#453]
There is a requirement that processes inside pod send data to processes on the host (outside the vm). Is there any API to do this? Or, any recommend method?

Thank you very much!

**Comment by laijs** [comment]
1） use network
2)  use shared filesystem
3)  use the slow stdio,   `hyperctl exec podid cmd | outer-process`

**Comment by GrantLajs** [comment]
Thanks for response.
Can I use domain socket, since the ip of vm and host could be in different ip domain?
And, shared filesystem is not good for protocol communication; stdio is lack of intercommunication.

**Comment by laijs** [comment]
you can use the network. (socket/bind/listen/accept with the vm ip & host-bridge-ip),
