### ISSUE TITLE
"hyperclt run" & "hyperctl exec" is not in the same workdir

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/hyperd#454]
First I run a pod with workdir specified as follows:
monster@monster-Z:~/go/src/github.com/hyperhq/hyperd$ sudo ./hyperctl run --workdir="/home" busybox
pwd
/home

Then I do exec in this pod:
monster@monster-Z:~/go/src/github.com/hyperhq/hyperd$ sudo ./hyperctl exec pod-vcVxlnXlha sh
pwd
/

Howerver, in docker, I do the same operation:
monster@monster-Z:~$ docker run -it -w /home busybox
/home # 

monster@monster-Z:~$ docker exec -it 50486804055c sh
/home # 

Maybe we should be consistent with docker

**Comment by gao-feng** [comment]
Fixed
