### ISSUE TITLE
How can I access the vm instead of the docker container?

### ISSUE THREAD

**Issue by GrantLajs** [hyperhq/hyperd#455]
I need to login to the VM, and install some drivers. However, so far, I can only attach to the pod, which is the docker container.
Is there any method to login to the VM and run shell?

Appreciate any response!

**Comment by gnawux** [comment]
Unfortunately, we didn't leave the backdoor.

At the very beginning, we had a debug mode to exec in the initramfs. But it was removed later.

**Comment by GrantLajs** [comment]
Is there any plan in future?
Device is visible to docker, but is disabled to vm without driver.

**Comment by gao-feng** [comment]
If you want to install some linux drivers(modules), you should compile the drivers and put them into the container, it's fine to install modules in container by insmod, you don't need to access the VM, we already support some drivers(modules) in hyper kernel, please check https://github.com/hyperhq/hyperstart/blob/master/build/kernel_config to get the modules we support.

**Comment by gnawux** [comment]
#533 add this feature again as it is requested by many debugging users.
