### ISSUE TITLE
`hyperctl run -t ` stuck

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hyperd#505]
```
$ sudo hyperctl run -t busybox sh
{}

```
When trying to run container with tty, it stucks. Non-tty mode and exec with tty is fine.

**Comment by gnawux** [comment]
This is a feature, this is not a bug.

**Comment by Crazykev** [comment]
@gnawux So run with tty is not supported anymore?  Why we still leave this flag here

**Comment by gnawux** [comment]
Let me check again

**Comment by gnawux** [comment]
@Crazykev What did you do exactly?

For me ,

```
-> sudo ./hyperctl run -t busybox /bin/sh
/ # ls
bin   dev   etc   home  lib   proc  root  sys   tmp   usr   var
/ # exit
-> 
```

The only thing not like before is (this is what I said "feature"):

```
-> sudo ./hyperctl list
POD ID               POD Name             VM name             Status
busybox-8525184801   busybox-8525184801   vm-hLwLLokFZp       running
->
```

i.e. Pod is still running although the container has already exited.

**Comment by Crazykev** [comment]
@gnawux I repeated exactly what I did (just start a hyperd and did what is above), everything is normal now.
So sorry, I can't reproduce it anymore. It's wired to me because operation is simple enough and this doesn't seem due to a config issue. 
Anyway, I'm gonna close this, if there is a change to meet it again, will dig deeper.
