### ISSUE TITLE
panic on delete pod 

### ISSUE THREAD

**Issue by gao-feng** [hyperhq/hyperd#519]
I0228 04:28:29.820131   78920 server.go:152] Calling DELETE /v0.7.0/image
E0228 04:28:29.820432   78920 server.go:170] Handler for DELETE /v0.7.0/image returned error: conflict: unable to remove repository reference "busybox" (must force) - container f79e43195838 is using its referenced image 7968321274dc
I0228 04:28:33.223608   78920 server.go:152] Calling DELETE /v0.7.0/image
I0228 04:28:38.294096   78920 server.go:152] Calling GET /v0.7.0/list
I0228 04:28:38.294213   78920 pod_routes.go:48] List type is pod, specified pod: [], specified vm: []
I0228 04:28:38.294275   78920 list.go:94] got list request for pod (pod: , vm: )
I0228 04:28:38.295486   78920 list.go:131] list pod result: [busybox-6208885741:busybox-6208885741:vm-lwyzCzIscP:running]
I0228 04:28:42.334509   78920 server.go:152] Calling DELETE /v0.7.0/pod
I0228 04:28:42.334640   78920 rm.go:30] remove pod busybox-6208885741, stop it firstly
I0228 04:28:42.334685   78920 decommission.go:387] Pod[busybox-6208885741] going to stop pod
I0228 04:28:42.334848   78920 decommission.go:451] Pod[busybox-6208885741] begin stop containers [f79e43195838d9134c61f88657c53a1ab157ffe976911a40645318984bf6255f]
I0228 04:28:42.334936   78920 decommission.go:463] Pod[busybox-6208885741] Con[f79e43195838(busybox-6208885741)] container state 2 is not running(3), ignore during stop
I0228 04:28:42.334987   78920 decommission.go:509] Pod[busybox-6208885741] complete stop containers [f79e43195838d9134c61f88657c53a1ab157ffe976911a40645318984bf6255f]
I0228 04:28:42.335023   78920 decommission.go:401] Pod[busybox-6208885741] stop container success, shutdown sandbox
I0228 04:28:42.335076   78920 hypervisor.go:23] vm vm-lwyzCzIscP: main event loop got message 9(COMMAND_SHUTDOWN)
I0228 04:28:42.335118   78920 vm_states.go:214] SB[vm-lwyzCzIscP] got shutdown command, shutting down
I0228 04:28:42.335157   78920 context.go:254] SB[vm-lwyzCzIscP] state change from RUNNING to 'TERMINATING'
I0228 04:28:42.335202   78920 serial.go:201] got cmd:4
I0228 04:28:42.335258   78920 serial.go:272] send command 4 to init, payload: 'null'.
E0228 04:28:42.637847   78920 hypervisor.go:49] SB[vm-lwyzCzIscP] watch hyperstart timeout
I0228 04:28:42.637900   78920 serial.go:65] close serialBasedHyperstart
I0228 04:28:42.637978   78920 hypervisor.go:23] vm vm-lwyzCzIscP: main event loop got message 16(ERROR_INIT_FAIL)
W0228 04:28:42.638015   78920 vm_states.go:207] got unexpected event during terminating
I0228 04:28:42.638044   78920 serial.go:198] vm channel closed, quit
E0228 04:28:42.638107   78920 hypervisor.go:42] SB[vm-lwyzCzIscP] hyperstart stopped
E0228 04:28:42.638133   78920 serial.go:111] read init data failed
W0228 04:28:42.638116   78920 vm_states.go:169] Destroy pod failed
I0228 04:28:42.638201   78920 serial.go:519] get hyperstart API version error: hyperstart closed
E0228 04:28:42.638201   78920 vm_states.go:177] Shutting down because of an exception: Destroy pod failed
I0228 04:28:42.638308   78920 vm_states.go:180] SB[vm-lwyzCzIscP] poweroff vm based on command: Destroy pod failed
I0228 04:28:42.638349   78920 context.go:235] SB[vm-lwyzCzIscP] VmContext Close()
I0228 04:28:42.638172   78920 serial.go:362] tty chan closed, quit sent goroutine
I0228 04:28:42.638155   78920 hypervisor.go:23] vm vm-lwyzCzIscP: main event loop got message 18(ERROR_INTERRUPTED)
I0228 04:28:42.638448   78920 vm_states.go:264] Connection interrupted while terminating: %shyperstart stopped
E0228 04:28:42.638163   78920 networks.go:85] Pod[busybox-6208885741] Nic[eth-default] failed to add NIC: hyperstart closed
I0228 04:28:42.638486   78920 hypervisor.go:23] vm vm-lwyzCzIscP: main event loop got message 16(ERROR_INIT_FAIL)
W0228 04:28:42.638518   78920 vm_states.go:207] got unexpected event during terminating
I0228 04:28:42.638411   78920 qemu_process.go:91] kill Qemu... 78991
E0228 04:28:42.638550   78920 provision.go:422] Pod[busybox-6208885741] error during add resources to sandbox: finished with errors: map[addInterface:hyperstart closed]
I0228 04:28:42.638589   78920 hypervisor.go:23] vm vm-lwyzCzIscP: main event loop got message 1(EVENT_VM_KILL)
E0228 04:28:42.638451   78920 serial.go:337] read tty data failed
I0228 04:28:42.638625   78920 vm_states.go:253] Got VM force killed message, go to cleaning up
I0228 04:28:42.638645   78920 serial.go:394] tty socket closed, quit the reading goroutine read unix @->/var/run/hyper/vm-lwyzCzIscP/tty.sock: use of closed network connection
I0228 04:28:42.638663   78920 context.go:235] SB[vm-lwyzCzIscP] VmContext Close()
I0228 04:28:42.638603   78920 vm_states.go:180] SB[vm-lwyzCzIscP] poweroff vm based on command: vm.Kill()
E0228 04:28:42.638711   78920 run.go:38] busybox-6208885741: failed to add pod: finished with errors: map[addInterface:hyperstart closed]
E0228 04:28:42.638750   78920 server.go:170] Handler for POST /v0.7.0/pod/create returned error: finished with errors: map[addInterface:hyperstart closed]
I0228 04:28:42.638784   78920 decommission.go:541] Pod[busybox-6208885741] got vm exit event
I0228 04:28:42.638727   78920 decommission.go:404] Pod[busybox-6208885741] pod is stopped
I0228 04:28:42.639038   78920 decommission.go:29] Pod[busybox-6208885741] pod stopped, now wait cleanup
I0228 04:28:42.639087   78920 decommission.go:584] Pod[busybox-6208885741] umount all containers and volumes, release IP addresses
I0228 04:28:42.653380   78920 container.go:1057] Pod[busybox-6208885741] Con[f79e43195838(busybox-6208885741)] umounted root volume
I0228 04:28:42.672439   78920 networks.go:95] Pod[busybox-6208885741] Nic[eth-default] release IP address: 192.168.222.2
I0228 04:28:42.672497   78920 etchosts.go:97] cleanupHosts /var/lib/hyper/hosts/busybox-6208885741, /var/lib/hyper/hosts/busybox-6208885741/hosts
I0228 04:28:42.680348   78920 decommission.go:569] Pod[busybox-6208885741] tag pod as stopped
I0228 04:28:42.680400   78920 decommission.go:576] Pod[busybox-6208885741] pod stopped
I0228 04:28:42.680446   78920 decommission.go:517] Pod[busybox-6208885741] got stop msg and push it again: stop container
I0228 04:28:42.680426   78920 qmp_handler.go:141] QMP exit as got error: EOF
I0228 04:28:42.680484   78920 decommission.go:523] Pod[busybox-6208885741] wait stop done: stop container
I0228 04:28:42.680634   78920 decommission.go:69] Pod[busybox-6208885741] removing pod
panic: send on closed channel

goroutine 113 [running]:
panic(0x11d6d00, 0x48209c62b0)
	/usr/lib/golang/src/runtime/panic.go:481 +0x384
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/qemu.(*QemuContext).Close(0x482146ac60)
	/root/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu.go:180 +0x4c
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).Close(0x4820b12c60)
	/root/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/context.go:240 +0x18c
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.stateTerminating(0x4820b12c60, 0x3ff75ec5db8, 0x48209e8048)
	/root/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/vm_states.go:255 +0x1ec
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).loop(0x4820b12c60)
	/root/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go:24 +0x530
created by github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).Launch
	/root/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go:91 +0x2b4
[root@leg hyperd]#

**Comment by gnawux** [comment]
Any update on this, @gao-feng ?

**Comment by gao-feng** [comment]
seems like fixed by https://github.com/hyperhq/runv/pull/457

**Comment by gnawux** [comment]
@gao-feng need update runV dep?

**Comment by gao-feng** [comment]
@gnawux https://github.com/hyperhq/hyperd/pull/568

**Comment by gnawux** [comment]
fixed by #568
