### ISSUE TITLE
Resource allocations

### ISSUE THREAD

**Issue by halacs** [hyperhq/hyperd#538]
Hi,

I am evaluating HyperContainer and it is not completely clear how resource allocation is different to VMs.

Where will be applied my resource constraints which I given in the POD definition? On container level, VM level or both?

Can I scale in/out any kind of resources (e.g. adding more RAM or CPU)?

Another question which was came up is the network limitation: in case of Hadoop network is a problematic resource type in limitation point of view. Here, can I apply network limitation somehow? It seems I can specify only the amount of CPU and RAM.

Thanks in advance!

Br,
Gabor Nyiri

**Comment by gnawux** [comment]
@halacs A pod of hypercontainer is run in a VM, and the resource constraints are applied to a pod (vm).

The memory and cpu are hotplug-able, however, we don't scale the resources now.

And for the network constraint, when use libvirt driver, we could limit some of the network parameters.

**Comment by gnawux** [comment]
This issue is included in the [Q&A page](https://docs.hypercontainer.io/internal/q_a.html) of HyperContainer Docs.

Thanks for your question @halacs
