### ISSUE TITLE
Curl method is not compatible for Debian Jessie (Debian 8.x)

### ISSUE THREAD

**Issue by kadogo** [hyperhq/hyperd#547]
Hello, I just tried to install hypercontainer with the curl method and I fall on these errors.

hypercontainer :
Depends: libdevmapper1.02.1 (>= 2:1.02.99) but 2:1.02.90-2.2+deb8u1 is to be installed
Depends: libvirt0 (>= 1.2.16-2ubuntu11.15.10.3) but 1.2.9-9+deb8u3 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

I don't have tried others method like ubuntu deb package or build from source.
Cheers.

**Comment by gnawux** [comment]
@kadogo Thanks for the report.

Confirm it. Will update them in the coming release (around this weekend).

**Comment by kadogo** [comment]
Perfect I will wait then ^^
Thanks.

**Comment by gnawux** [comment]
New deb packages are built from debian jessie, and work for both debian jessie and ubuntu xenial
