### ISSUE TITLE
Kill container with tty failed

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hyperd#549]
How to reproduce:
```
$ sudo hyperctl run -t -d busybox sh
POD id is busybox-2151895508
Time to run a POD is 2573 ms
$ sudo hyperctl list container
Container ID                                                       Name                 POD ID               Status
e2e7649b5c8d3306160fe403a7ebd370cf45fac17a11865afc893ba619230007   busybox-2151895508   busybox-2151895508   running
$ sudo hyperctl stop -c e2e7649b5c8d3306160fe403a7ebd370cf45fac17a11865afc893ba619230007
fail to stop container e2e7649b5c8d3306160fe403a7ebd370cf45fac17a11865afc893ba619230007: Error from daemon's response: chan broken while waiting containers: map[string]bool{"e2e7649b5c8d3306160fe403a7ebd370cf45fac17a11865afc893ba619230007":true}
```

**Comment by gnawux** [comment]
how about try without `-t` flag, or `kill` with signal 9

**Comment by gnawux** [comment]
@Crazykev Let me explain, the stop container kill container with its `StopSignal`.

In the `busybox` image, the `StopSignal` is `SIGTERM`, which works well in non-tty mode. However, if the `sh` of `busybox` run in tty mode, `SIGTERM` will be ignored.  Instead, only SIGKILL works. More or less, I think this is an busybox issue.

A general solution is kill with `SIGKILL` if stop not takes into effect in several seconds.

**Comment by Crazykev** [comment]
@gnawux Thanks, I've understood this. But I still think this is an(part of?) issue in hyperd, could we stop container just like we stop pod, if can't stop it with default(image specified) signal in graceful time, we need kill it with `SIGKILL` and return normally.
I've tried in docker, container exit with status `Exited (137)`, seems container have been killed.

**Comment by gnawux** [comment]
@Crazykev Yes, I agree. Are you willing to add this mechanism? Or I will check if any other have time to make this fix now.

**Comment by Crazykev** [comment]
@gnawux Glad to do this. Will do it later today or tomorrow
