### ISSUE TITLE
sometimes qemu start failed (or serial port interrupted) when the kernel initialize serial device

### ISSUE THREAD

**Issue by gnawux** [hyperhq/hyperd#557]
This issue listed two cases:

- The first case is described in hyperhq/hyperstart#285 and fixed in hyperhq/hyperstart#286

> 'TestSuite.TestSendContainerSignal' failed to end as attached.
> 
> In the test matrix, it's high probability there are one job (and only one) out of five jobs failed. And if > restart the job, it will pass.
> 
> [log-toolong.txt](https://github.com/hyperhq/hyperd/files/852579/log-toolong.txt)

- The second case is qemu stop/interrupted when guest initializing serial device.

And the remain disscussion of this thread is about the second case.

**Comment by gnawux** [comment]
```I0317 16:49:45.829586   23145 json.go:521] get hyperstart API version error: send ctl channel error, the hyperstart might have closed
```

**Comment by gnawux** [comment]
```
I0317 10:34:55.297563   23218 decommission.go:544] Pod[busybox] got vm exit event
I0317 10:34:55.297575   23218 decommission.go:592] Pod[busybox] umount all containers and volumes, release IP addresses
I0317 10:34:55.297588   23218 etchosts.go:97] cleanupHosts /var/lib/hyper/hosts/busybox, /var/lib/hyper/hosts/busybox/hosts
I0317 10:34:55.297616   23218 etchosts.go:101] cannot find /var/lib/hyper/hosts/busybox/hosts
I0317 10:34:55.297708   23218 decommission.go:572] Pod[busybox] sandbox info removed from db
I0317 10:34:55.297719   23218 decommission.go:577] Pod[busybox] tag pod as stopped
I0317 10:34:55.297726   23218 decommission.go:584] Pod[busybox] pod stopped
I0317 10:34:58.021414   23218 json.go:521] get hyperstart API version error: send ctl channel error, the hyperstart might have closed
E0317 10:35:19.764693   23218 hypervisor.go:49] SB[vm-QeEPbljMVQ] watch hyperstart timeout
```

another case, on `TestSuite.TestCreateAndStartPod`
[log-toolong-1.txt](https://github.com/hyperhq/hyperd/files/852586/log-toolong-1.txt)

**Comment by gnawux** [comment]
another similar one on `TestSuite.TestRenameContainer`
[log-toolong-2.txt](https://github.com/hyperhq/hyperd/files/852588/log-toolong-2.txt)

**Comment by gnawux** [comment]
I think it's more or less related with the hyperstart protocol handling, at least, it should not stall here if the protocol state machine transits to an illegal state. @laijs could you check this one?

**Comment by gnawux** [comment]
looks the serial port disconnected while the kernel init the serial device...

```
I0316 16:48:30.441463   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] virtio-pci 0000:00:02.0: virtio_pci: leaving for legacy driver
I0316 16:48:30.447921   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 11
I0316 16:48:30.448010   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] virtio-pci 0000:00:03.0: virtio_pci: leaving for legacy driver
I0316 16:48:30.453452   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
I0316 16:48:30.453663   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] virtio-pci 0000:00:04.0: virtio_pci: leaving for legacy driver
I0316 16:48:30.458682   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
I0316 16:48:30.459030   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] virtio-pci 0000:00:05.0: virtio_pci: leaving for legacy driver
```

Based on the console message, Interrupt here, do you have any ideas @bergwolf @gao-feng ?

```
I0316 16:48:30.465716   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
I0316 16:48:30.489577   23090 vm_console.go:46] SB[vm-CRDiGlKuWp] [CNL] 00:04: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
```

**Comment by gnawux** [comment]
the #554 is the same problem.

[log-test-stopped.txt](https://github.com/hyperhq/hyperd/files/849581/log-test-stopped.txt)

**Comment by gao-feng** [comment]
not quite sure if this bug is fixed by https://github.com/golang/go/commit/5bcdd639331cd7f8d844fd38a674c4751423f938

**Comment by gnawux** [comment]
@gao-feng go 1.8 only?

**Comment by bergwolf** [comment]
we would never read with zero length buffer:
```
        buf := make([]byte, 512)
        res := []byte{}
        for read < needRead {
                want := needRead - read
                if want > 512 {
                        want = 512
                }
                nr, err := conn.Read(buf[:want])
```

**Comment by gnawux** [comment]
looks this commit is included in both 1.7 and 1.8.

**Comment by gnawux** [comment]
The qemu in travis testing is 2.0.0

**Comment by gnawux** [comment]
The qemu in jenkins belongs to ubuntu 16.04, and version is 2.5. This issue spread in both 2.0 and 2.5, and should be a guest kernel issue?

**Comment by gnawux** [comment]
some cases from Jenkins

- http://ci.hypercontainer.io:8080/job/hyperd-auto/304/console
- http://ci.hypercontainer.io:8080/job/hyperd-auto/302/console

I checked about 20 recent build failures, all of this cases were happened with `libvirt` driver, and no qemu driver meet the init interrupt problem.

**Comment by bergwolf** [comment]
libvirt ended up using qemu command line:
`-chardev socket,id=charchannel0,path=/var/run/hyper/vm-vBrtiilBzU/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=sh.hyper.channel.0`

while qemu driver uses:
`-serial unix:/var/run/hyper/vm-UGcRAJrPUR/console.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0`

**Comment by bergwolf** [comment]
full command lines comparison. 
libvirt:
`/usr/bin/qemu-system-x86_64 -name vm-lWRHQAOeCW -S -machine pc-i440fx-2.0,accel=tcg,usb=off -cpu Broadwell,+abm,+pdpe1gb,+hypervisor,+rdrand,+f16c,+osxsave,+ss,+vme -m 128 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid f2728ef7-a964-47ce-8f8e-e45703988361 -nographic -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-vm-lWRHQAOeCW/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-reboot -boot strict=on -kernel /var/lib/hyper/kernel -initrd /var/lib/hyper/hyper-initrd.img -append console=ttyS0 panic=1 no_timer_check -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -fsdev local,security_model=none,id=fsdev-fs0,path=/var/run/hyper/vm-lWRHQAOeCW/share_dir -device virtio-9p-pci,id=fs0,fsdev=fsdev-fs0,mount_tag=share_dir,bus=pci.0,addr=0x4 -chardev socket,id=charserial0,path=/var/run/hyper/vm-lWRHQAOeCW/console.sock,server,nowait -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,path=/var/run/hyper/vm-lWRHQAOeCW/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charchannel1,path=/var/run/hyper/vm-lWRHQAOeCW/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=sh.hyper.channel.1 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -msg timestamp=on`

qemu:
`/bin/qemu-system-x86_64 -machine pc-i440fx-2.0,usb=off -cpu core2duo -kernel /var/lib/hyper/kernel -initrd /var/lib/hyper/hyper-initrd.img -append console=ttyS0 panic=1 no_timer_check -realtime mlock=off -no-user-config -nodefaults -no-hpet -rtc base=utc,driftfix=slew -no-reboot -display none -boot strict=on -m 128 -smp 1 -qmp unix:/var/run/hyper/vm-oXLmDUBhSp/qmp.sock,server,nowait -serial unix:/var/run/hyper/vm-oXLmDUBhSp/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -chardev socket,id=charch0,path=/var/run/hyper/vm-oXLmDUBhSp/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/hyper/vm-oXLmDUBhSp/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -fsdev local,id=virtio9p,path=/var/run/hyper/vm-oXLmDUBhSp/share_dir,security_model=none -device virtio-9p-pci,fsdev=virtio9p,mount_tag=share_dir -daemonize -pidfile /var/run/hyper/vm-oXLmDUBhSp/pidfile -D /var/log/hyper/qemu/vm-oXLmDUBhS.log`

**Comment by gnawux** [comment]
didn't happen in recent Hykins, but still in travis, such as: 
[log-serial.txt](https://github.com/hyperhq/hyperd/files/972751/log-serial.txt)

**Comment by bergwolf** [comment]
PRs for hyperd/runv travis are not merged yet
https://github.com/hyperhq/hyperd/pull/611
https://github.com/hyperhq/runv/pull/493

**Comment by bergwolf** [comment]
hykins/travis both use in-house built qemu now. Reopen if this is seen again.
