### ISSUE TITLE
GRPC server fatal before clean up vm in hyperd

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hyperd#560]
if we enable GRPC server in hyperd and shutdown it with SIGINT or SIGTERM, hyperd will stop server through [`stopServer()`](https://github.com/hyperhq/hyperd/blob/master/hyperd.go#L214), which will make [`rpcServer.Serve()`](https://github.com/hyperhq/hyperd/blob/master/hyperd.go#L171) report an error and exit before hyperd could finish clean up VM in `d.DestroyAllVm()`. 

It's easy to fix this, but I'm not sure what's the best way.

**Comment by gnawux** [comment]
change `glog.Fatalf` to `glog.Errorf`?

**Comment by Crazykev** [comment]
If `rpcServer.Serve()` failed at beginning, seems we do need `glog.Fatalf`...

**Comment by gao-feng** [comment]
closed by https://github.com/hyperhq/hyperd/pull/567
