### ISSUE TITLE
Support user not in /etc/passwd

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hyperd#572]
This is major reason test fail in https://github.com/kubernetes/frakti/issues/109

Can be reproduced with image `gcr.io/google_containers/mounttest-user:0.5`
This image specified `"User": "1001"`, but rootfs has only `mt` binary.

/cc @feiskyer

**Comment by feiskyer** [comment]
@gnawux @gao-feng Any ideas on this?

**Comment by gao-feng** [comment]
had better post hyperd logs, seems we should regard "user": "1001" as a valid configuration even hyperstart cannot find it in /etc/passwd. @laijs

**Comment by Crazykev** [comment]
here is complete v3 [log](https://gist.github.com/Crazykev/d2727d046b9c1f0a2b25eabce19cc44d)

**Comment by laijs** [comment]
failed to open /etc/passwd: No such file or directory

**Comment by gao-feng** [comment]
https://github.com/hyperhq/hyperstart/pull/283

**Comment by feiskyer** [comment]
Fixed by hyperhq/hyperstart#283.
