### ISSUE TITLE
ubuntu package and panic with log_dir

### ISSUE THREAD

**Issue by matti** [hyperhq/hyperd#588]
On Ubuntu 16.04 after installing the .deb:

```
$ hyperd
hyperd flag redefined: log_dir
panic: hyperd flag redefined: log_dir
...
```

**Comment by gnawux** [comment]
The packages in http://download.hypercontainer.io/ have been updated

**Comment by gnawux** [comment]
The release page has been updated

**Comment by matti** [comment]
to me it seems like (see my recent issues) that hyperd is not really tested with anything else than with centos -- I used centos and the pre-built packages and everything worked fine.

Should I just use centos and forget ubuntu etc?

**Comment by gnawux** [comment]
@matti All the packages were built from the same sources.

The deb package problems had been found right after the release when we did the kubernetes tests with it. However, only the download site has been updated with new packages, and the github release page was left. 

I have updated the github release page, and centralized all the packages to our download site.

**Comment by matti** [comment]
@gnawux thanks ok!

**Comment by gnawux** [comment]
You are welcome.
