### ISSUE TITLE
Compile with xen in ubuntu

### ISSUE THREAD

**Issue by matti** [hyperhq/hyperd#591]
I have installed xen and devel packages on ubuntu 16.04

`./configure`

**Comment by gnawux** [comment]
There is a build issue with latest xen, and it will fix with future release.

**Comment by matti** [comment]
(I'm only compiling from the source since there are no pre-built binaries)

**Comment by matti** [comment]
So can I use an older xen? Which version and how should I install it?

**Comment by matti** [comment]
(Can I install packages or should I install it from the source, the docs are very thin here @gnawux)

**Comment by gnawux** [comment]
Do you mean you want use Xen

**Comment by matti** [comment]
yes instead of qemu.

**Comment by gnawux** [comment]
You may try with with xen 4.5

**Comment by gnawux** [comment]
fixed by hyperhq/runv#484
