### ISSUE TITLE
runv not needed for just hyperd/hyperctl ?

### ISSUE THREAD

**Issue by matti** [hyperhq/hyperd#594]
In https://docs.hypercontainer.io/get_started/install/build.html

there is a line:
```
> git clone https://github.com/hyperhq/runv.git runv
```

but no compile / use instructions.

**Comment by gnawux** [comment]
It's a code dependency of hyperd, and it is included in the vendor of the newest release of hyperd, i.e. don't need to clone it for build hyperd now.

**Comment by matti** [comment]
so the docs should be updated if I'm reading you correctly?

**Comment by gnawux** [comment]
Yes, the steps should be updated.

**Comment by gnawux** [comment]
the docs has been updated
