### ISSUE TITLE
mac hyperctl

### ISSUE THREAD

**Issue by matti** [hyperhq/hyperd#596]
This page https://github.com/hyperhq/docs.hypercontainer.io/blob/master/get_started/install/mac.md

that is not linked from the docs (?) has a download link for a package that installs "hyper", but no "hyperctl" (like it should according to the latest commit message to that file)

Are you still maintaining mac builds? I think that hyperctl would be super useful to have as a pre-built thing.

**Comment by gnawux** [comment]
The Mac version had been disabled, and the link to this page had been removed form the TOC.

**Comment by matti** [comment]
@gnawux can you help me out building one? or is it not doable anymore?

```
make
Making all in mac_installer
make[1]: Nothing to be done for `all'.
go build -tags "static_build   exclude_graphdriver_btrfs libdm_no_deferred_remove" -ldflags "-X github.com/hyperhq/hyperd/utils.VERSION=0.8.0 -X github.com/hyperhq/hyperd/utils.GITCOMMIT=`git describe`" hyperd.go
hyperd.go:11:2: cannot find package "github.com/docker/docker/opts" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/github.com/docker/docker/opts (from $GOROOT)
	/Users/mpa/.go/src/github.com/docker/docker/opts (from $GOPATH)
hyperd.go:20:2: cannot find package "github.com/docker/docker/pkg/parsers/kernel" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/github.com/docker/docker/pkg/parsers/kernel (from $GOROOT)
	/Users/mpa/.go/src/github.com/docker/docker/pkg/parsers/kernel (from $GOPATH)
```

**Comment by gnawux** [comment]
Mac OS X build is not available in current version, and I closed this issue. However, it's always welcome if you could work on it and submit PR for it if you like to make a client for Mac.
