### ISSUE TITLE
Error while running hyperctl info

### ISSUE THREAD

**Issue by bruceherve** [hyperhq/hyperd#645]
@laijs I know this is an old issue but I ran into the same issue  I even posted on slack but so far not much help from there.. but I  get the same error when I run hyperctl info:
hyperctl ERROR: An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fhyper.sock/v0.8.1/list?item=pod: dial unix /var/run/hyper.sock: connect: no such file or directory

**and here is the log as you suggested:**

Log file created at: 2017/06/24 20:57:49
Running on machine: localhost
Binary: Built with gc go1.8.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0624 20:57:49.122851 18247 config.go:38] config file: %!(EXTRA string=/etc/hyper/config)
I0624 20:57:49.123234 18247 config.go:72] [/etc/hyper/config] config items: &types.HyperConfig{ConfigFile:"/etc/hyper/config", Root:"/var/lib/hyper", Host:"", GRPCHost:"", StorageDriver:"", VmFactoryPolicy:"", Driver:"qemu", Kernel:"/var/lib/hyper/kernel", Initrd:"/var/lib/hyper/hyper-initrd.img", Bridge:"", BridgeIP:"", DisableIptables:false, EnableVsock:true, DefaultLog:"", DefaultLogOpt:map[string]string{}, logPrefix:"[/etc/hyper/config] "}
I0624 20:57:55.170355 18247 daemon.go:215] The hypervisor's driver is qemu
I0624 20:57:56.299793 18247 migration.go:23] Migrate lagecy persistent pod data, found: 0, migrated: 0
I0624 20:57:56.310088 18247 hyperd.go:189] Hyper daemon: 0.8.1 v0.4.0-912-g7a07c71
I0624 20:58:37.811799 18247 daemon.go:357] The daemon will be shutdown
I0624 20:58:37.811826 18247 daemon.go:358] Shutdown all VMs

**Comment by gnawux** [comment]
Did the daemon shutdown by yourself or the OS? Try increase the `hyperd` log level with `-v=4`

**Comment by bruceherve** [comment]
No it is the OS

**Comment by gnawux** [comment]
Then check what's the problem with OS. Based on the current logs, It's hard to judge what's the matter.

**Comment by bruceherve** [comment]
Actually I had to compile from source because I was unable to install using the bash script.. I am using Linux korora 25 but It's just Fedora 25 under the hood.. I mean:
**uname -a**
Linux localhost.localdomain **4.11.5-200.fc25.x86_64** #1 SMP Wed Jun 14 17:17:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Or is it a problem when using Fedora beacuse I also tried to install hyper on machine running project atomic/fedora25 but It complained saying it only supports Fedora 23..but i believe it is mentioned on github that fedora 25 is supported..

**Comment by gnawux** [comment]
Build from source won't break anything and FC25 is supported as well.

**Comment by gnawux** [comment]
As I mentioned in the first comment, try increase the log level, maybe we could found why it quit.

**Comment by bruceherve** [comment]
Thanks a lot @gnawux . It's now working!!
Here are the issues and steps I took in case someone else gets the same problem..
1. cd /etc/hyper  and uncomment  the Hypervisor line and assign a value accordingly(libvirt,kvm,qemu)
2. enable hyper daemon with **systemctl enable hyperd**
3. start hyper daemon with **systemctl start hyperd**
N.B: step 2 and 3 only apply if you are using **systemd**, for example ubuntu 14  is still on **init** so adjust accordingly..
4. **systemctl status hyperd** if you get running and enabled you are good to go
5. **sudo hyperctl** list works!!

**Comment by gnawux** [comment]
Good to know it works. And the default hypervisor would be qemu if no one is specified, as shown in the log

```
I0624 20:57:55.170355 18247 daemon.go:215] The hypervisor's driver is qemu
```

**Comment by bruceherve** [comment]
Yeah, I see..well I guess you can close this one. next stop Hypernetes!!

**Comment by gnawux** [comment]
Enjoy it 👍
