### ISSUE TITLE
Incorrect build instructions in the manual

### ISSUE THREAD

**Issue by punitagrawal** [hyperhq/hyperd#650]
I get an error about missing packages (pasted below) while building hyper from source following the steps from the manual - https://docs.hypercontainer.io/get_started/install/build.html. The build machine is a VM running debian unstable.

I fixed the error by running

`cd <GOPATH>/src/github.com
git clone https://github.com/moby/moby docker`

As docker repositories have moved, ideally the packages should be renamed. Also, the build instructions need to be updated to call out the docker source dependencies.

I get the following error when running "make".

% make
make[1]: Entering directory '~/go/github.com/hyperhq/hyperd'
go build -tags "static_build  with_libvirt exclude_graphdriver_btrfs libdm_no_deferred_remove" -ldflags "-X github.com/hyperhq/hyperd/utils.VERSION=0.8.1 -X github.com/hyperhq/hyperd/utils.GITCOMMIT=`git describe`" hyperd.go
hyperd.go:11:2: cannot find package "github.com/docker/docker/opts" in any of:
        /usr/lib/go-1.8/src/github.com/docker/docker/opts (from $GOROOT)
        ~/go/src/github.com/docker/docker/opts (from $GOPATH)
hyperd.go:20:2: cannot find package "github.com/docker/docker/pkg/parsers/kernel" in any of:
        /usr/lib/go-1.8/src/github.com/docker/docker/pkg/parsers/kernel (from $GOROOT)
        ~/go/src/github.com/docker/docker/pkg/parsers/kernel (from $GOPATH)
hyperd.go:12:2: cannot find package "github.com/docker/docker/pkg/reexec" in any of:
        /usr/lib/go-1.8/src/github.com/docker/docker/pkg/reexec (from $GOROOT)
        ~/go/src/github.com/docker/docker/pkg/reexec (from $GOPATH)
hyperd.go:13:2: cannot find package "github.com/golang/glog" in any of:
        /usr/lib/go-1.8/src/github.com/golang/glog (from $GOROOT)
        ~/go/src/github.com/golang/glog (from $GOPATH)
hyperd.go:14:2: cannot find package "github.com/hyperhq/hyperd/daemon" in any of:
        /usr/lib/go-1.8/src/github.com/hyperhq/hyperd/daemon (from $GOROOT)
        ~/go/src/github.com/hyperhq/hyperd/daemon (from $GOPATH)
hyperd.go:15:2: cannot find package "github.com/hyperhq/hyperd/server" in any of:
        /usr/lib/go-1.8/src/github.com/hyperhq/hyperd/server (from $GOROOT)
        ~/go/src/github.com/hyperhq/hyperd/server (from $GOPATH)
hyperd.go:16:2: cannot find package "github.com/hyperhq/hyperd/serverrpc" in any of:
        /usr/lib/go-1.8/src/github.com/hyperhq/hyperd/serverrpc (from $GOROOT)
        ~/go/src/github.com/hyperhq/hyperd/serverrpc (from $GOPATH)
hyperd.go:17:2: cannot find package "github.com/hyperhq/hyperd/types" in any of:
        /usr/lib/go-1.8/src/github.com/hyperhq/hyperd/types (from $GOROOT)
        ~/go/src/github.com/hyperhq/hyperd/types (from $GOPATH)
hyperd.go:18:2: cannot find package "github.com/hyperhq/hyperd/utils" in any of:
        /usr/lib/go-1.8/src/github.com/hyperhq/hyperd/utils (from $GOROOT)
        ~/go/src/github.com/hyperhq/hyperd/utils (from $GOPATH)
Makefile:790: recipe for target 'build-hyperd' failed
make[1]: *** [build-hyperd] Error 1
make[1]: Leaving directory '~/go/github.com/hyperhq/hyperd'
Makefile:363: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by laijs** [comment]
All the dependent packages are in the vendor/ directory. It is strange that this directory was not being searched when you built the hyperd.

**Comment by gnawux** [comment]
@punitagrawal what's the Go version ?

**Comment by punitagrawal** [comment]
I found out what I was doing wrong - instead of "<GOPATH>/src" I had cloned the repository in "<GOPATH>". I think that was why I got the build failures.

Sorry for the noise. I can build when I _correctly_ follow the instructions.

For reference, the go version on the system -

% go version
go version go1.8.3 linux/amd64

**Comment by gnawux** [comment]
Thank you for the response @punitagrawal
