### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by m-barthelemy** [hyperhq/hyperd#676]
Hi,

I tried multiple times to build the current master branch (218df4254009c1084a342e28b7e537bfed4d1eff), with both go 1.8 and 1.9.
I'm following this doc: https://docs.hypercontainer.io/get_started/install/build.html

Getting the following error:
```
$ make
Making all in cmd
make[1]: Entering directory '/src/github.com/hyperhq/hyperd/cmd'
Making all in hyperd
make[2]: Entering directory '/src/github.com/hyperhq/hyperd/cmd/hyperd'
go build -tags "static_build   exclude_graphdriver_btrfs libdm_no_deferred_remove" -ldflags "-X github.com/hyperhq/hyperd/utils.VERSION=1.0.0 -X github.com/hyperhq/hyperd/utils.GITCOMMIT=`git describe --dirty --always --tags 2> /dev/null || true`" hyperd.go
# command-line-arguments
./hyperd.go:144: cannot use defaultHost (type string) as type bool in argument to opts.ParseHost
Makefile:452: recipe for target 'build-hyperd' failed
make[2]: *** [build-hyperd] Error 2
make[2]: Leaving directory '/src/github.com/hyperhq/hyperd/cmd/hyperd'
Makefile:330: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/src/github.com/hyperhq/hyperd/cmd'
Makefile:355: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```

OS: Ubuntu Xenial (16.04)

Go: 
```
$ go version
go version go1.8.3 linux/amd64
```

Since nothing seems to have changed recently in this part of hyperd.go, what am I doing wrong?

**Comment by gnawux** [comment]
Hi @m-barthelemy , could you show the `GOPATH` environment?

Actually the official rpm and deb binary packages are built with the same source as well, and the build was done inside a clean docker image (ref: https://github.com/hyperhq/hyperd/tree/master/package). I think the FTBFS should be related with environments.

**Comment by m-barthelemy** [comment]
Hi,
thanks for the quick reply.
Will try a fresh nw build using the official tool. Closing this one.
