### ISSUE TITLE
Expired SSL cert for project site

### ISSUE THREAD

**Issue by ukd1** [hyperhq/hyperd#734]
<img width="880" alt="screen shot 2018-07-09 at 8 41 44 pm" src="https://user-images.githubusercontent.com/44345/42488048-950be0e4-83b8-11e8-86ec-b841c8f3c4a2.png">

**Comment by gnawux** [comment]
will check it asap, thanks for reporting @ukd1

**Comment by gnawux** [comment]
Fixed by @Jimmy-Xu 

The cert expiration is caused by an out-of-date certbot, and we enabled auto-upgrade of it now.
