### ISSUE TITLE
Hyperd Socket log following stops after a short time

### ISSUE THREAD

**Issue by njlie** [hyperhq/hyperd#739]
Replication steps:
Launch a pod with a container whose image continuously outputs (e.g. "Hello World" and a counter over and over) to stdout with `hyperctl run`.
Attach a stream to the standard output of the container with the hyper socket with `follow=true`:
`/container/logs?container=CONTAINER_NAME&stdout=true&follow=true`

After a (varying) short amount of time, the stream on the Hyper socket will stop, while the output from `hyperctl run` will continue to output.

edit: The image I used to test this was [feraltc/printforever](https://hub.docker.com/r/feraltc/printforever/)

**Comment by gnawux** [comment]
@teawater any ideas on this?

**Comment by teawater** [comment]
@njlie @gnawux I reproduced this issue in my part and working on it.
