### ISSUE TITLE
Hyperd is not working:failed to load sandbox info: leveldb

### ISSUE THREAD

**Issue by kuthreecar** [hyperhq/hyperd#748]
I installed the hyperd on CentOS as usual, and it could run actively, but it got different errors according to status. Anyone knows where is the problem?

Here is the status:
> Nov 13 07:56:39 aaa systemd[1]: Starting hyperd...
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=info msg="[graphdriver] using prior storage driver "devicemapper""
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=info msg="Firewalld running: false"
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=info msg="Loading containers: start."
Nov 13 07:56:39 aaa hyperd[5638]: .
Nov 13 07:56:39 aaa hyperd[5638]: time="2018-11-13T07:56:39Z" level=info msg="Loading containers: done."
Nov 13 07:56:39 aaa hyperd[5638]: E1113 07:56:39.506112    5638 persist.go:117] Pod[hello-world-0328860666] failed to load sandbox info: leveldb: not found key: SB-hello-world-0328860666

**Comment by bergwolf** [comment]
@kuthreecar 
>failed to load sandbox info: leveldb: not found key: SB-hello-world-0328860666

This is not a fatal error and is ignored during hyperd startup. Could you please post the full debug log (e.g. by starting hyperd in command line with `sudo hyperd --v=9 --alsologtostderr`), so that we can see what actually stopped hyperd from working? Thanks!

**Comment by kuthreecar** [comment]
@bergwolf
Thanks, since I was deployed it on aws, I relaunched a instance and reinstalled hyperd. now have no problem for that, I may close this issue first, thanks.
