### ISSUE TITLE
Future after shutting down Hyper.sh

### ISSUE THREAD

**Issue by szepeviktor** [hyperhq/hyperd#750]
Do you plan to stop active development after Hyper.sh shutdown?

**Comment by desimmons** [comment]
What has happened to this project? It seems to have many interesting project that depend on it: https://github.com/kubernetes/frakti , https://github.com/codius/codiusd

However, it seems to be completely non functional. The hypercontainer.io website doesn't work. There are essentially no resources online. And I am completely unable to get this repo to provide any functionality ...

Is the project depreciated?

**Comment by szepeviktor** [comment]
@teawater Could you comment?

**Comment by desimmons** [comment]
https://github.com/codius/codiusd/issues/150#issuecomment-483040576

**Comment by szepeviktor** [comment]
Thank you.
